/* R3 regression: physical parcel time, rigid blade path, integration ownership. */
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const E=require('../src/vfx3/runtime.js');
const from={x:668,y:459,w:116,h:146},to={x:932,y:295,w:116,h:146};
const d=(kind='breath',scale=1,seed=388)=>E.descriptor(kind,{from,to,startedAt:0,contactAt:260*scale,timeScale:scale,hitStopMs:50*scale,seed});
function geom(){const c={console,Math,Float32Array,performance:{now:()=>0}};c.window=c;vm.createContext(c);vm.runInContext(fs.readFileSync('src/vfx3/renderer.js','utf8').split('(function(X)')[0],c);c.Ember3D.Renderer=class{constructor(){this.geo={plane:{}};this.dynamic={}}mesh(data){return{data,n:data.length/8}}resize(){}camera(){}};vm.runInContext(fs.readFileSync('src/vfx3/runtime.js','utf8'),c);return c.EmberVFX3.create({});}
const near=(a,b,t=1e-6)=>assert.ok(Math.abs(a-b)<=t,`${a} ≠ ${b}`);
test('R3 flame does not exist before its own birth or after its life',()=>{const a=d(),c=E.breathClock(a,0);assert.equal(E.flameParcel(a,10,0),null);let p=E.flameParcel(a,10,c.launch+10*c.interval+.001);assert.ok(p);assert.equal(E.flameParcel(a,10,p.birth+p.life+.001),null);});
test('R3 leading parcel arrives exactly at the authoritative impact',()=>{const a=d(),p=E.flameParcel(a,0,.260);near(p.u,1);near(p.along,1);});
test('R3 no later faster parcel beats the initial contact',()=>{const a=d();for(let i=0;i<30;i++)for(let t=.05;t<.259;t+=.007){const p=E.flameParcel(a,i,t);if(p)assert.ok(p.u<1.000001);}});
test('R3 axial position AND velocity stay continuous when jet turns at contact',()=>{const a=d(),c=E.breathClock(a,0),i=14,p=E.flameParcel(a,i,c.launch+i*c.interval+.001),t=p.birth+p.flight,e=1e-7;const l=E.flameParcel(a,i,t-e),m=E.flameParcel(a,i,t),r=E.flameParcel(a,i,t+e);near((m.along-l.along)/e,(r.along-m.along)/e,.001);});
test('R3 sustained jet retains parcels between source and contact',()=>{const a=d();for(const t of [.40,.60,.80]){const live=Array.from({length:160},(_,i)=>E.flameParcel(a,i,t)).filter(p=>p&&p.alpha>.08);assert.ok(live.filter(p=>p.along<.5).length>=3);assert.ok(live.filter(p=>p.along>.7&&p.along<1).length>=3);}});
test('R3 material parcels preserve aspect and finite geometry through all phases',()=>{const a=d();for(let t=0;t<1.7;t+=.01)for(let i=0;i<140;i++){const p=E.flameParcel(a,i,t);if(!p)continue;for(const v of Object.values(p))assert.ok(Number.isFinite(v));assert.ok(p.w>p.h&&p.h>0);assert.ok(p.alpha>=0&&p.alpha<=1);}});
test('R3 fixed seed supports arbitrary seek order without random regeneration',()=>{const a=d(),p=E.flameParcel(a,12,.46);E.flameParcel(a,80,.85);assert.deepEqual(E.flameParcel(a,12,.46),p);assert.notDeepEqual(E.flameParcel(d('breath',1,52),12,.46),p);});
test('R3 compressed time preserves parcel phase and shape',()=>{const a=d(),b=d('breath',.5);for(const t of [.15,.3,.5,.8])for(let i=0;i<40;i++){const p=E.flameParcel(a,i,t),q=E.flameParcel(b,i,t*.5);if(!p){assert.equal(q,null);continue;}for(const k of ['age','along','w','h','alpha','angle'])near(p[k],q[k]);}});
test('R3 smoke and already emitted fire fully finish before declared cleanup',()=>{const a=d();for(let i=0;i<180;i++)assert.equal(E.flameParcel(a,i,(a.impact+a.tail)/1000),null);});
test('R3 sword has a readable back-cock followed by a faster downward sweep',()=>{const a=d('slash'),m0=E.cleaveMotion(a,.01),m1=E.cleaveMotion(a,.065),m2=E.cleaveMotion(a,.23),m3=E.cleaveMotion(a,.26);assert.ok(m1.angle>m0.angle);assert.ok(m2.angle<m1.angle);near(m3.angle,Math.PI);assert.ok(m2.drop<1);});
test('R3 blade stays rigid for mirrored attackers, tiny and large cards',()=>{const r=geom();for(const w of [52,116,220])for(const side of [-1,1]){const a=E.descriptor('slash',{from:{...from,x:to.x+side*260},to:{...to,w},contactAt:260,hitStopMs:50});let min=Infinity,max=0;for(let t=0;t<.95;t+=.004){const p=r._swordPose(a,t),l=Math.hypot(...p.tip.map((x,i)=>x-p.root[i]));min=Math.min(min,l);max=Math.max(max,l);}assert.ok(max-min<.001);}});
test('R3 actual sword tip remains planted throughout impact hold and only then withdraws',()=>{const r=geom(),a=d('slash'),hit=r._swordPose(a,.26);for(const t of [.26,.275,.295,.31,.42]){const p=r._swordPose(a,t);assert.ok(Math.hypot(...p.tip.map((x,i)=>x-hit.tip[i]))<.001);}assert.ok(r._swordPose(a,.80).tip[1]>hit.tip[1]);});
test('R3 sword position is continuous at phase boundaries',()=>{const r=geom(),a=d('slash');for(const t of [.26*.29,.26,.31,.54,.82]){const l=r._swordPose(a,t-1e-6),q=r._swordPose(a,t+1e-6);assert.ok(Math.hypot(...l.tip.map((x,i)=>x-q.tip[i]))<.02);}});
test('R3 frame sampling cannot write to damage or game state',()=>{const s=fs.readFileSync('src/vfx3/runtime.js','utf8');for(const x of ['.dispatch(','.hp=','game.s','setTimeout('])assert.ok(!s.includes(x));});
test('R3 reference fire palette is retained without an extra duplicated hot coat',()=>{const shader=fs.readFileSync('src/vfx3/renderer.js','utf8');assert.ok(shader.includes('gold=vec3(2.7,.56,.018),white=vec3(3.7,1.7,.31)'));const s=fs.readFileSync('src/vfx3/runtime.js','utf8').split(' function fire(')[1].split(' function draw(now)')[0];assert.ok(!s.includes('mode:11'));assert.ok(s.includes('plumes.sort'));});
test('R3 queued material draws carry their own shader clock',()=>{const s=fs.readFileSync('src/vfx3/renderer.js','utf8');assert.ok(s.includes('Number.isFinite(opt.time)?opt.time:this.time'));const r=fs.readFileSync('src/vfx3/runtime.js','utf8');assert.ok(r.includes('time:.96+s.t/d.scale'));});
test('R3 prelude owns the same attack instance; old lift launch is skipped',()=>{const s=fs.readFileSync('src/effects.js','utf8');assert.ok(s.includes('rec.meshPrelude = true'));assert.ok(s.includes('sequence.records.get(i)?.meshPrelude'));assert.ok(s.includes('contactAt: sequence.origin + beat.at + m.contact'));});
