/* R4: source-fidelity is tested against the actual original demo, not against
 * new expected values generated by the port. See fixtures/reference-flame.json. */
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),crypto=require('node:crypto');
const R=require('../src/vfx3/reference-flame.js'),E=require('../src/vfx3/runtime.js');
const fixtures=require('./fixtures/reference-flame.json');
const from={x:668,y:459,w:116,h:146},to={x:932,y:295,w:116,h:146};
const desc=(scale=1)=>E.descriptor('breath',{from,to,startedAt:0,contactAt:260*scale,timeScale:scale,seed:388});
const norm=x=>Array.isArray(x)?x.map(norm):x&&typeof x==='object'?Object.fromEntries(Object.entries(x).map(([k,v])=>[k,norm(v)])):typeof x==='number'?Math.round(x*1e6)/1e6:x;
const sha=s=>crypto.createHash('sha256').update(s).digest('hex');
const close=(a,b,e=1e-5)=>assert.ok(Math.abs(a-b)<e,`${a} differs from ${b}`);
for(const f of fixtures.samples)test(`original flame exact output @${f.time}s density=${f.density}`,()=>{
 const frame=R.sample(f.time,f.density);assert.equal(sha(JSON.stringify(norm(frame))),f.sha256);
 for(const [k,n]of Object.entries(f.counts))assert.equal(frame[k].length,n);
});
test('flame and smoke GLSL are identical to the reference source branches',()=>{
 const src=fs.readFileSync('src/vfx3/renderer.js','utf8');
 assert.equal(src.slice(src.indexOf('if(uMode>7.5'),src.indexOf('if(uMode>8.5')),R.shader);
 assert.equal(src.slice(src.indexOf('if(uMode>8.5'),src.indexOf('if(uMode>9.5')),R.smokeShader);
});
test('all reference parcels keep their authored lifetime, finite geometry and fixed opacity bounds',()=>{
 for(let t=0;t<5.4;t+=.037){const q=R.sample(t);for(const p of q.sprites){assert.ok(p.w>0&&p.h>0);assert.ok(p.alpha>=0&&p.alpha<=1);p.pos.forEach(x=>assert.ok(Number.isFinite(x)));}}
});
test('same reference field supports arbitrary seek order without mutation',()=>{
 const before=R.sample(2.0);R.sample(4.0);R.sample(0);assert.deepEqual(R.sample(2.0),before);
});
test('reference charge, continuous firing, smoke tail and finished state are distinct',()=>{
 assert.equal(R.sample(.8).sprites.filter(x=>x.mode===8).length,0);
 for(const t of [1.65,2.2,2.7,3.15])assert.ok(R.sample(t).sprites.filter(x=>x.mode===8).length>30);
 assert.equal(R.sample(4.3).sprites.filter(x=>x.mode===8).length,0);
 assert.ok(R.sample(4.3).sprites.filter(x=>x.mode===9).length>0);
 assert.equal(R.sample(5.5).sprites.length,0);
});
test('host preserves contact deadline and advances original post-contact time at 1:1',()=>{
 const d=desc();close(E.breathClock(d,.26).time,1.46);
 close(E.breathClock(d,1.26).time,2.46);close(E.breathClock(d,2.26).time,3.46);
 for(const x of [.1,.26,.4,1.2])close(E.breathClock(desc(.5),x*.5).time,E.breathClock(d,x).time);
});
test('host phase mapping is continuous on the authoritative contact boundary',()=>{
 const d=desc();assert.ok(Math.abs(E.breathClock(d,.26-1e-7).time-E.breathClock(d,.26+1e-7).time)<1e-5);
 assert.equal(d.impact,260);
});
test('single similarity transform preserves distances and billboard proportions',()=>{
 const d=desc(),m=E.flameMapping(d,1600,940),a=[0,0,0],b=[1,2,3],p=m.point(a),q=m.point(b);
 close(Math.hypot(...q.map((v,i)=>v-p[i])),Math.hypot(...b)*m.scale);
 const sample=R.sample(2).sprites[0];close((sample.w*m.scale)/(sample.h*m.scale),sample.w/sample.h);
});
test('emitter and reference contact centre map to the existing source and target boxes',()=>{
 const m=E.flameMapping(desc(),1600,940),f=m.point(R.mouth(.96)),t=m.point([2.68,1.70,0]);
 close(f[0],m.F[0]);close(f[1],m.F[1]);close(t[0],m.T[0]);close(t[1],m.T[1]);
});
test('degenerate/short/vertical/reversed paths still produce finite transformations',()=>{
 for(const q of [from,{...to,x:from.x}, {...to,x:12,y:800}, {...from,x:from.x+1}]){
  const d=E.descriptor('breath',{from,to:q,contactAt:0});const m=E.flameMapping(d,390,844);
  m.point([2,1,0]).forEach(x=>assert.ok(Number.isFinite(x)));assert.ok(m.scale>0);
  assert.ok(Number.isFinite(E.breathClock(d,0).time));
 }
});
test('cleanup deadline is beyond all original fire/smoke parcels',()=>{
 for(const scale of [.1,.5,1]){const d=desc(scale),t=E.breathClock(d,(d.impact+d.tail)/1000).time;
  assert.equal(R.sample(t).sprites.length,0);assert.equal(R.sample(t).particles.length,0);
 }
});
test('reference module creates no dragon model, rule mutation, timer or render context',()=>{
 const s=fs.readFileSync('src/vfx3/reference-flame.js','utf8');
 for(const x of ['new Renderer','getContext(','buildDragon(','game.dispatch','EmberDebug','requestAnimationFrame(','setTimeout('])assert.ok(!s.includes(x),x);
});
test('CPU reference sampler loads before the renderer/runtime and only the host rotates output',()=>{
 const t=fs.readFileSync('src/template.html','utf8');assert.ok(t.indexOf('/*MESH_REFERENCE*/')<t.indexOf('/*MESH_RENDERER*/'));
 for(const token of ['MESH_REFERENCE','MESH_RENDERER','MESH_RUNTIME'])assert.ok(t.includes('<script>/*'+token+'*/</script>'),'one script token per tag: '+token);
 const host=fs.readFileSync('src/vfx3/runtime.js','utf8');assert.ok(host.includes('Ref.sample(clock.time'));assert.ok(host.includes('plumes.sort'));
 assert.ok(!host.includes('function flameParcel('));
});
test('transparent fire uses reference exposure and premultiplied energy before tone mapping',()=>{
 const s=fs.readFileSync('src/vfx3/renderer.js','utf8');assert.ok(s.includes('tone((s.rgb+b)*.97)'));assert.ok(s.includes('uReferenceFlame'));
});
test('contact-only reference glow is gated by the existing rule deadline',()=>{
 assert.ok(fs.readFileSync('src/vfx3/runtime.js','utf8').includes('if(s.after<0&&p.pos[0]>2)continue;'));
});
