/* Authored campaign definitions. Text is generated from effects. */
const EmberCampaign = {
  heroes: [
    {
      id: "mage",
      name: "星焰法师",
      title: "艾莉娅",
      sub: "ARCANE & EMBER",
      art: "mage",
      palette: "arcane",
      power: "星火",
      target: "enemy",
      desc: "以烈焰与寒霜掌控战局，用法术完成致命一击。",
      deck: [
        "spark",
        "spark",
        "squire",
        "wolf",
        "guard",
        "guard",
        "oracle",
        "oracle",
        "wisp",
        "sentinel",
        "golem",
        "cleric",
        "phoenix",
        "rider",
        "paladin",
        "dragon",
        "nyx",
        "ashdragon",
        "bolt",
        "bolt",
        "frostbolt",
        "frostbolt",
        "fireball",
        "fireball",
        "nova",
        "wisdom",
        "renew",
        "storm",
        "polymorph",
        "discovery",
      ],
      powerCost: 2,
      powerEffects: [
        {
          type: "damage",
          amount: 1,
          to: "selected",
          spell: false,
        },
      ],
      portraitId: "oracle",
    },
    {
      id: "paladin",
      name: "黎明圣卫",
      title: "雷昂",
      sub: "LIGHT & HONOR",
      art: "knight",
      palette: "gold",
      power: "征召",
      desc: "坚守誓约，集结圣盾军团，在号角声中反击。",
      deck: [
        "squire",
        "squire",
        "spark",
        "wolf",
        "guard",
        "guard",
        "oracle",
        "sentinel",
        "cleric",
        "cleric",
        "golem",
        "golem",
        "berserker",
        "treant",
        "phoenix",
        "necromancer",
        "paladin",
        "paladin",
        "titan",
        "solaris",
        "colossus",
        "blessing",
        "blessing",
        "renew",
        "rally",
        "rally",
        "shield",
        "shield",
        "sunblade",
        "ambush",
      ],
      powerCost: 2,
      powerEffects: [
        {
          type: "summon",
          card: "recruit",
          count: 1,
          requireSpace: true,
        },
      ],
      portraitId: "paladin",
    },
    {
      id: "ranger",
      name: "暗影游侠",
      title: "薇丝珀",
      sub: "WILD & SHADOW",
      art: "archer",
      palette: "nature",
      power: "穿心箭",
      desc: "驾驭野兽与暗影，利用突袭和武器夺取先机。",
      deck: [
        "wolf",
        "wolf",
        "archer",
        "archer",
        "squire",
        "sentinel",
        "sentinel",
        "spider",
        "spider",
        "guard",
        "oracle",
        "assassin",
        "assassin",
        "leech",
        "berserker",
        "rider",
        "rider",
        "huntress",
        "huntress",
        "reaper",
        "colossus",
        "bolt",
        "wolves",
        "wolves",
        "dagger",
        "dagger",
        "lifedrain",
        "execute",
        "silence",
        "battlecry",
      ],
      powerCost: 2,
      powerEffects: [
        {
          type: "damage",
          amount: 2,
          to: "enemyHero",
          spell: false,
        },
      ],
      portraitId: "archer",
    },
  ],
  bosses: [
    {
      id: "warden",
      name: "灰烬监守",
      title: "余火之门",
      en: "THE ASHEN WARDEN",
      art: "knight",
      palette: "ember",
      hp: 30,
      power: "余烬之怒",
      quote: "每一簇反抗的火焰，都将在此熄灭。",
      deck: [
        "squire",
        "spark",
        "guard",
        "sentinel",
        "bolt",
        "golem",
        "berserker",
        "cleric",
        "fireball",
        "phoenix",
        "titan",
        "dragon",
        "wisdom",
        "dagger",
        "renew",
      ],
      color: "#d47742",
      powerCost: 2,
      powerEffects: [
        {
          type: "damage",
          amount: 2,
          to: "enemyHero",
          spell: false,
        },
      ],
      phaseEffects: [
        {
          type: "armor",
          amount: 5,
        },
        {
          type: "summon",
          card: "guard",
          count: 1,
        },
      ],
      portraitId: "berserker",
    },
    {
      id: "queen",
      name: "荆棘女王",
      title: "低语密林",
      en: "THE THORN QUEEN",
      art: "treant",
      palette: "nature",
      hp: 34,
      power: "蔓生",
      quote: "听见了吗？树根正在呼唤你的名字。",
      deck: [
        "wolf",
        "archer",
        "spider",
        "guard",
        "treant",
        "wolves",
        "blessing",
        "rally",
        "renew",
        "golem",
        "oracle",
        "huntress",
        "colossus",
        "silence",
        "sentinel",
      ],
      color: "#8bb773",
      powerCost: 2,
      powerEffects: [
        {
          type: "summon",
          card: "thorn",
          count: 1,
          requireSpace: true,
        },
      ],
      phaseEffects: [
        {
          type: "buff",
          attack: 1,
          health: 2,
          to: "friendlyMinions",
        },
      ],
      portraitId: "treant",
    },
    {
      id: "oracle",
      name: "深渊先知",
      title: "无光圣所",
      en: "THE ABYSSAL ORACLE",
      art: "mage",
      palette: "void",
      hp: 36,
      power: "灵魂汲取",
      quote: "你所看见的终点，不过是我的序章。",
      deck: [
        "leech",
        "assassin",
        "oracle",
        "wisp",
        "necromancer",
        "reaper",
        "lifedrain",
        "execute",
        "discovery",
        "ambush",
        "silence",
        "wisdom",
        "wolf",
        "guard",
        "nyx",
      ],
      color: "#a889d1",
      powerCost: 2,
      powerEffects: [
        {
          type: "damage",
          amount: 1,
          to: "enemyHero",
          spell: false,
        },
        {
          type: "heal",
          amount: 2,
        },
      ],
      phaseEffects: [
        {
          type: "summon",
          card: "leech",
          count: 2,
        },
      ],
      portraitId: "necromancer",
    },
    {
      id: "frost",
      name: "霜狱君王",
      title: "永冻王座",
      en: "THE FROSTBOUND KING",
      art: "reaper",
      palette: "ice",
      hp: 40,
      power: "凛冬触碰",
      quote: "时间在此凝结，希望也不例外。",
      deck: [
        "squire",
        "guard",
        "golem",
        "rider",
        "frostbolt",
        "nova",
        "oracle",
        "paladin",
        "titan",
        "frostking",
        "colossus",
        "wisdom",
        "polymorph",
        "renew",
        "sentinel",
      ],
      color: "#79c9d9",
      powerCost: 2,
      powerEffects: [
        {
          type: "randomDamageFreeze",
          amount: 1,
        },
      ],
      phaseEffects: [
        {
          type: "armor",
          amount: 8,
        },
        {
          type: "freeze",
          to: "enemyMinions",
        },
      ],
      portraitId: "frostking",
    },
    {
      id: "dragon",
      name: "终焉巨龙",
      title: "世界之烬",
      en: "THE WORLD ENDER",
      art: "dragon",
      palette: "blood",
      hp: 45,
      power: "焚界吐息",
      quote: "在最后一颗星辰熄灭之前，燃烧吧。",
      deck: [
        "spark",
        "guard",
        "sentinel",
        "bolt",
        "berserker",
        "golem",
        "phoenix",
        "rider",
        "fireball",
        "dragon",
        "ashdragon",
        "titan",
        "paladin",
        "storm",
        "renew",
      ],
      color: "#df7059",
      powerCost: 3,
      powerEffects: [
        {
          type: "damage",
          amount: 1,
          to: "enemies",
          spell: false,
        },
      ],
      phaseEffects: [
        {
          type: "damage",
          amount: 2,
          to: "enemies",
          spell: false,
        },
        {
          type: "summon",
          card: "dragon",
          count: 1,
        },
      ],
      portraitId: "ashdragon",
    },
  ],
  relics: [
    {
      id: "heart",
      name: "不熄之心",
      icon: "heart",
      maxHealth: 8,
    },
    {
      id: "lens",
      name: "星界透镜",
      icon: "orb",
      spellDamage: 1,
    },
    {
      id: "crown",
      name: "晨曦王冠",
      icon: "sigil",
      onStart: [
        {
          type: "armor",
          amount: 7,
        },
      ],
    },
    {
      id: "feather",
      name: "渡鸦之羽",
      icon: "raven",
      onTurn: [
        {
          type: "heal",
          amount: 2,
        },
      ],
    },
    {
      id: "ember",
      name: "初火余烬",
      icon: "bolt",
      startingMana: 1,
    },
    {
      id: "banner",
      name: "誓约战旗",
      icon: "banner",
      onStart: [
        {
          type: "summon",
          card: "squire",
          count: 1,
        },
      ],
    },
  ],
  kw: {
    taunt: "嘲讽",
    shield: "圣盾",
    rush: "突袭",
    charge: "冲锋",
    lifesteal: "吸血",
    poison: "剧毒",
    windfury: "风怒",
    stealth: "潜行",
    reborn: "复生",
    spellpower: "法术伤害 +1",
  },
};
if (typeof module !== "undefined") module.exports = EmberCampaign;
