/* Authored campaign and archetypes. */
const EmberCampaign = {
  classes: [
    {
      id: "neutral",
      name: "中立",
    },
    {
      id: "mage",
      name: "法师",
    },
    {
      id: "paladin",
      name: "圣卫",
    },
    {
      id: "ranger",
      name: "游侠",
    },
    {
      id: "foe",
      name: "对手",
    },
  ],
  tribes: [
    {
      id: "beast",
      name: "野兽",
    },
    {
      id: "undead",
      name: "亡灵",
    },
    {
      id: "dragon",
      name: "龙",
    },
  ],
  deckRules: {
    size: 30,
    maxCopies: 2,
    rarityCopies: {
      legendary: 1,
    },
  },
  heroes: [
    {
      id: "mage",
      classId: "mage",
      powerIcon: "fire",
      name: "鉴珀师",
      title: "娜希拉",
      sub: "ARCANE & EMBER",
      art: "mage",
      palette: "arcane",
      power: "星火",
      target: "enemy",
      desc: "以烈焰与寒霜掌控战局，用法术完成致命一击。",
      defaultDeckId: "pantheon_stars",
      powerCost: 2,
      powerEffects: [
        {
          type: "damage",
          amount: 1,
          to: "selected",
          spell: false,
        },
      ],
      portraitId: "nahira",
      defaultContracts: ["jingchen"],
    },
    {
      id: "paladin",
      classId: "paladin",
      powerIcon: "banner",
      name: "背誓骑士",
      title: "菲德莉亚",
      sub: "LIGHT & HONOR",
      art: "knight",
      palette: "gold",
      power: "征召",
      desc: "坚守誓约，集结圣盾军团，在号角声中反击。",
      defaultDeckId: "pantheon_dawn",
      powerCost: 2,
      powerEffects: [
        {
          type: "summon",
          card: "recruit",
          count: 1,
          requireSpace: true,
        },
      ],
      portraitId: "frederia",
      defaultContracts: ["aurion"],
    },
    {
      id: "ranger",
      classId: "ranger",
      powerIcon: "bow",
      name: "守林人",
      title: "罗温",
      sub: "WILD & SHADOW",
      art: "archer",
      palette: "nature",
      power: "穿心箭",
      desc: "驾驭野兽与暗影，利用突袭和武器夺取先机。",
      defaultDeckId: "pantheon_hunt",
      powerCost: 2,
      powerEffects: [
        {
          type: "damage",
          amount: 2,
          to: "enemyHero",
          spell: false,
        },
      ],
      portraitId: "rowan",
      defaultContracts: ["fenlos"],
    },
    {
      id: "morla",
      classId: "ranger",
      powerIcon: "lantern",
      name: "提灯人",
      title: "利奥尔",
      sub: "MOON & MEMORY",
      art: "mage",
      palette: "void",
      power: "送魂灯",
      target: "friendlyMinion",
      desc: "以献祭兑现亡语，收集灵魂印记，唤醒冥月契约。",
      defaultDeckId: "moon_covenant",
      powerCost: 2,
      powerEffects: [
        {
          type: "sacrifice",
          to: "selected",
        },
        {
          type: "draw",
          count: 1,
        },
      ],
      portraitId: "liol",
      defaultContracts: ["eclipsewolf", "moonguard", "selmyra"],
    },
  ],
  bosses: [
    {
      id: "warden",
      name: "铁哨",
      title: "矿区监工",
      en: "IRONWHISTLE",
      art: "knight",
      palette: "ember",
      discoverClass: "mage",
      hp: 30,
      power: "长哨",
      quote: "他从不开口。哨声一响，两百个矿工同时向前。",
      deck: [
        "squire",
        "spark",
        "guard",
        "sentinel",
        "bolt",
        "golem",
        "berserker",
        "cleric",
        "fireball",
        "phoenix",
        "titan",
        "dragon",
        "wisdom",
        "dagger",
        "shield",
      ],
      color: "#d47742",
      powerCost: 2,
      powerEffects: [
        {
          type: "damage",
          amount: 1,
          to: "enemyHero",
          spell: false,
        },
      ],
      phaseEffects: [
        {
          type: "armor",
          amount: 3,
        },
        {
          type: "summon",
          card: "guard",
          count: 1,
        },
      ],
      portraitId: "whistle",
    },
    {
      id: "queen",
      name: "根母",
      title: "被钻机逼疯的守护灵",
      en: "THE ROOT MOTHER",
      art: "treant",
      palette: "nature",
      discoverClass: "mage",
      hp: 34,
      power: "蔓生",
      quote: "疼……你们的钻头，一直钻到我的心里。",
      deck: [
        "wolf",
        "archer",
        "spider",
        "guard",
        "treant",
        "wolves",
        "blessing",
        "rally",
        "muster",
        "golem",
        "oracle",
        "huntress",
        "tracking",
        "absolution",
        "sentinel",
      ],
      color: "#8bb773",
      powerCost: 2,
      powerEffects: [
        {
          type: "summon",
          card: "thorn",
          count: 1,
          requireSpace: true,
        },
      ],
      phaseEffects: [
        {
          type: "buff",
          attack: 1,
          health: 2,
          to: "friendlyMinions",
        },
      ],
      portraitId: "rootmother",
    },
    {
      id: "oracle",
      name: "译者",
      title: "《根海手札》的破译者",
      en: "THE TRANSLATOR",
      art: "mage",
      palette: "void",
      discoverClass: "mage",
      hp: 36,
      power: "灵魂汲取",
      quote: "我读过你下一张牌。别担心，我读得很慢，你来得及后悔。",
      deck: [
        "leech",
        "assassin",
        "oracle",
        "wisp",
        "necromancer",
        "reaper",
        "lifedrain",
        "execute",
        "discovery",
        "counterspell",
        "silence",
        "wisdom",
        "wolf",
        "guard",
        "nyx",
      ],
      color: "#a889d1",
      powerCost: 2,
      powerEffects: [
        {
          type: "damage",
          amount: 1,
          to: "enemyHero",
          spell: false,
        },
        {
          type: "heal",
          amount: 2,
        },
      ],
      phaseEffects: [
        {
          type: "summon",
          card: "leech",
          count: 2,
        },
      ],
      portraitId: "translator",
    },
    {
      id: "frost",
      name: "守根人",
      title: "冻在井里的根战英雄",
      en: "THE ROOT KEEPER",
      art: "reaper",
      palette: "ice",
      discoverClass: "mage",
      hp: 40,
      power: "凛冬触碰",
      quote: "三千年了。往下走的人，我拦下过每一个。",
      deck: [
        "squire",
        "guard",
        "golem",
        "rider",
        "frostbolt",
        "nova",
        "oracle",
        "paladin",
        "titan",
        "frostking",
        "icebarrier",
        "wisdom",
        "polymorph",
        "renew",
        "sentinel",
      ],
      color: "#79c9d9",
      powerCost: 2,
      powerEffects: [
        {
          type: "randomDamageFreeze",
          amount: 1,
        },
      ],
      phaseEffects: [
        {
          type: "armor",
          amount: 8,
        },
        {
          type: "freeze",
          to: "enemyMinions",
        },
      ],
      portraitId: "rootkeeper",
    },
    {
      id: "dragon",
      name: "点火者·纳坦",
      title: "总工程师",
      en: "NATAN, THE IGNITER",
      art: "dragon",
      palette: "blood",
      discoverClass: "mage",
      hp: 42,
      power: "锅炉过载",
      quote: "我不恨你们。我只是在等你们，把钥匙送下来。",
      deck: [
        "spark",
        "guard",
        "sentinel",
        "bolt",
        "berserker",
        "golem",
        "phoenix",
        "rider",
        "fireball",
        "dragon",
        "ashdragon",
        "titan",
        "paladin",
        "storm",
        "renew",
      ],
      color: "#df7059",
      powerCost: 3,
      powerEffects: [
        {
          type: "damage",
          amount: 1,
          to: "enemies",
          spell: false,
        },
      ],
      phaseEffects: [
        {
          type: "damage",
          amount: 2,
          to: "enemies",
          spell: false,
        },
        {
          type: "summon",
          card: "dragon",
          count: 1,
        },
      ],
      portraitId: "nathan",
    },
    {
      id: "moonkeeper",
      name: "守灯之兽",
      title: "引路的夫人留在边界的神兽",
      en: "THE LAMP BEAST",
      art: "mage",
      palette: "void",
      discoverClass: "mage",
      hp: 40,
      power: "封契之刃",
      quote: "（它不说话。它只是把灯，往你这边偏了一寸。）",
      deck: [
        "guard",
        "oracle",
        "sentinel",
        "moonfox",
        "duskstag",
        "soulguide",
        "stillness",
        "polymorph",
        "moonlance",
        "necromancer",
        "lifedrain",
        "reaper",
        "titan",
        "wisdom",
        "silence",
      ],
      color: "#a889d1",
      powerCost: 3,
      powerEffects: [
        {
          type: "randomDamageFreeze",
          amount: 2,
        },
      ],
      phaseEffects: [
        {
          type: "summon",
          card: "moonguard",
          count: 1,
        },
      ],
      portraitId: "lampbeast",
    },
    {
      id: "fuse",
      name: "引信",
      title: "爆破队的少女",
      en: "FUSE",
      art: "archer",
      palette: "ember",
      discoverClass: "mage",
      hp: 28,
      power: "倒数",
      quote: "三、二……你们别跑啊，我还没数到一呢！",
      deck: ["spark", "wisp", "bolt", "spider", "berserker", "dagger", "fireball", "guard", "assassin", "nova", "golem", "sentinel", "phoenix", "storm", "execute", "fusecord"],
      color: "#d8793a",
      powerCost: 2,
      powerEffects: [{"type": "damage", "amount": 1, "to": "enemyHero", "spell": false}],
      phaseEffects: [{"type": "damage", "amount": 2, "to": "enemies", "spell": false}],
      portraitId: "fuse",
    },
    {
      id: "gleaner",
      name: "拾珀人",
      title: "塌方现场的拾荒者",
      en: "THE AMBER GLEANER",
      art: "rogue",
      palette: "void",
      discoverClass: "mage",
      hp: 30,
      power: "撬珀",
      quote: "这块还带着体温。你不要了吧？",
      deck: ["wolf", "spider", "assassin", "dagger", "tracking", "sabotage", "guard", "oracle", "cleric", "berserker", "leech", "reaper", "battlecry", "ambush", "sentinel", "glean"],
      color: "#a8946a",
      powerCost: 2,
      powerEffects: [{"type": "draw", "count": 1}],
      phaseEffects: [{"type": "armor", "amount": 3}, {"type": "summon", "card": "stone", "count": 1}],
      portraitId: "gleaner",
    },
    {
      id: "appraiser",
      name: "估价人",
      title: "联邦估价官",
      en: "THE APPRAISER",
      art: "golem",
      palette: "arcane",
      discoverClass: "mage",
      hp: 30,
      power: "加征",
      quote: "每一样东西都有价格。你的，我已经算好了。",
      deck: ["silence", "guard", "sentinel", "cleric", "oracle", "golem", "counterspell", "polymorph", "icebarrier", "wisdom", "discovery", "frostbolt", "frostwhisper", "mirrormage", "titan", "appraise"],
      color: "#9aa6b8",
      powerCost: 2,
      powerEffects: [{"type": "randomDamageFreeze", "amount": 1}],
      phaseEffects: [{"type": "freeze", "to": "enemyMinions"}],
      portraitId: "appraiser",
    },
    {
      id: "redscarf",
      name: "红围巾",
      title: "罢工的矿工首领",
      en: "RED SCARF",
      art: "knight",
      palette: "gold",
      discoverClass: "mage",
      hp: 32,
      power: "团结",
      quote: "你是公司的人。可你的手……怎么也是黑的？",
      deck: ["squire", "muster", "rally", "guard", "acolyte", "vowguard", "sentinel", "blessing", "wolf", "wolves", "cleric", "berserker", "battlecry", "tortoise", "absolution", "strikecrowd"],
      color: "#c0554a",
      powerCost: 2,
      powerEffects: [{"type": "summon", "card": "recruit", "count": 1, "requireSpace": true}],
      phaseEffects: [{"type": "buff", "attack": 1, "health": 1, "to": "friendlyMinions"}],
      portraitId: "redscarf",
    },
    {
      id: "drill",
      name: "第七号掘进机",
      title: "蒸汽钻机",
      en: "THE SEVENTH DRILL",
      art: "golem",
      palette: "ember",
      discoverClass: "mage",
      hp: 36,
      power: "钻进",
      quote: "……天，现在是什么颜色的？",
      deck: ["golem", "sentinel", "guard", "titan", "colossus", "vowguard", "oathkeeper", "bloodknight", "tortoise", "frostgolem", "berserker", "treant", "cleric", "rider", "dragon", "drillbit"],
      color: "#c07a3c",
      powerCost: 2,
      powerEffects: [{"type": "armor", "amount": 2}],
      phaseEffects: [{"type": "armor", "amount": 6}, {"type": "damage", "amount": 3, "to": "enemies", "spell": false}],
      portraitId: "drill",
    },
    {
      id: "clockmaker",
      name: "钟表匠",
      title: "联邦的发条兵设计师",
      en: "THE CLOCKMAKER",
      art: "golem",
      palette: "arcane",
      discoverClass: "mage",
      hp: 34,
      power: "上发条",
      quote: "它们不会死在塌方里。这就够了。",
      deck: ["golem", "titan", "frostgolem", "magmacore", "colossus", "sentinel", "guard", "oathkeeper", "mirrormage", "rider", "wisdom", "spark", "bolt", "fireball", "wisp", "clockworksergeant"],
      color: "#b8925a",
      powerCost: 2,
      powerEffects: [{"type": "summon", "card": "stone", "count": 1, "requireSpace": true}],
      phaseEffects: [{"type": "buff", "attack": 1, "health": 2, "to": "friendlyMinions"}],
      portraitId: "clockmaker",
    },
    {
      id: "blacklung",
      name: "黑肺",
      title: "肺里长了黑玉的矿工",
      en: "THE BLACK LUNG",
      art: "reaper",
      palette: "void",
      discoverClass: "mage",
      hp: 34,
      power: "咳血",
      quote: "咳……别怕，这不会传染。至少……不会马上。",
      deck: ["gravewatch", "leech", "necromancer", "bloodknight", "reaper", "bonelord", "lifedrain", "assassin", "graveoffering", "soultether", "spider", "guard", "cleric", "execute", "soulguide", "blackcough"],
      color: "#4f8f86",
      powerCost: 2,
      powerEffects: [{"type": "damage", "amount": 1, "to": "enemyHero", "spell": false}, {"type": "heal", "amount": 1}],
      phaseEffects: [{"type": "summon", "card": "skeleton", "count": 2}],
      portraitId: "blacklung",
    },
    {
      id: "ada",
      name: "艾达",
      title: "总工近卫统领",
      en: "ADA BRANDT",
      art: "knight",
      palette: "gold",
      discoverClass: "mage",
      hp: 40,
      power: "校准",
      quote: "我不是来阻止你们的。我是来把父亲带回来的。",
      deck: ["squire", "shield", "acolyte", "vowguard", "dawnrider", "archbishop", "golem", "titan", "consecrate", "judgment", "blessing", "renew", "sentinel", "guard", "absolution", "calibrate"],
      color: "#d49a4a",
      powerCost: 2,
      powerEffects: [{"type": "summon", "card": "recruit", "count": 1, "requireSpace": true}],
      phaseEffects: [{"type": "armor", "amount": 5}, {"type": "buff", "attack": 1, "health": 1, "to": "friendlyMinions"}],
      portraitId: "ada",
    },
    {
      id: "earlyriser",
      name: "早醒者",
      title: "被砸出琥珀的远古巨兽",
      en: "THE EARLY RISER",
      art: "golem",
      palette: "nature",
      discoverClass: "mage",
      hp: 40,
      power: "痛吼",
      quote: "（一声压过矿井的、不是愤怒而是疼的吼叫。）",
      deck: ["boar", "tortoise", "rider", "treant", "huntress", "berserker", "titan", "golem", "colossus", "dragon", "wolves", "spider", "rider", "guard", "sentinel", "earlyroar"],
      color: "#a8782e",
      powerCost: 2,
      powerEffects: [{"type": "damage", "amount": 1, "to": "enemyMinions", "spell": false}],
      phaseEffects: [{"type": "summon", "card": "stone", "count": 2}, {"type": "buff", "attack": 1, "health": 1, "to": "friendlyMinions"}],
      portraitId: "earlyriser",
    },
    {
      id: "amberbody",
      name: "琥珀之躯",
      title: "半张脸封进琥珀的改造兵",
      en: "THE AMBER-BODIED",
      art: "knight",
      palette: "gold",
      discoverClass: "mage",
      hp: 32,
      power: "琥珀装甲",
      quote: "不疼。它替我记着，我就不用记了。",
      deck: ["guard", "sentinel", "acolyte", "vowguard", "dawnrider", "golem", "titan", "mirrormage", "oathkeeper", "sunblade", "shield", "blessing", "consecrate", "renew", "absolution", "archbishop", "amberplate"],
      color: "#d49a2e",
      powerCost: 2,
      powerEffects: [{"type": "armor", "amount": 2}],
      phaseEffects: [{"type": "armor", "amount": 6}],
      portraitId: "amberbody",
    },
    {
      id: "pawnbroker",
      name: "典当人",
      title: "当铺栅栏后的老人",
      en: "THE PAWNBROKER",
      art: "rogue",
      palette: "void",
      discoverClass: "mage",
      hp: 24,
      power: "抵押",
      quote: "东西留下，日子拿走。放心，利息算得很公道。",
      deck: ["silence", "counterspell", "stillness", "polymorph", "discovery", "wisdom", "ambush", "icebarrier", "guard", "oracle", "cleric", "scribe", "sentinel", "bolt", "pawnticket"],
      color: "#8f7a4f",
      powerCost: 2,
      powerEffects: [{"type": "draw", "count": 1}],
      phaseEffects: [{"type": "armor", "amount": 4}],
      portraitId: "pawnbroker",
    },
    {
      id: "mirrorlegion",
      name: "倒影军团",
      title: "黑玉面甲的另一边士兵",
      en: "THE MIRROR LEGION",
      art: "knight",
      palette: "void",
      discoverClass: "mage",
      hp: 44,
      power: "列阵",
      quote: "（所有人同时抬起了头。没有人开口。）",
      deck: ["squire", "acolyte", "vowguard", "dawnrider", "archer", "dagger", "assassin", "spark", "wisp", "mirrormage", "ambush", "counterspell", "muster", "rally", "archbishop", "mirrorfile"],
      color: "#5d6b76",
      powerCost: 2,
      powerEffects: [{"type": "summon", "card": "recruit", "count": 1, "requireSpace": true}],
      phaseEffects: [{"type": "summon", "card": "skeleton", "count": 2}, {"type": "buff", "attack": 1, "health": 1, "to": "friendlyMinions"}],
      portraitId: "mirrorlegion",
    },
    {
      id: "mirrornahira",
      name: "镜中的娜希拉",
      title: "另一边的鉴珀师",
      en: "THE MIRRORED APPRAISER",
      art: "mage",
      palette: "void",
      discoverClass: "mage",
      hp: 38,
      power: "倒映星火",
      quote: "你在柜台后面也这样看过别人吧。看出价钱，看不出人。",
      deck: ["guard", "oracle", "golem", "cleric", "treant", "frostbolt", "nova", "polymorph", "wisdom", "icebarrier", "fireball", "storm", "discovery", "frostking", "nyx", "starweave"],
      color: "#7b57c4",
      powerCost: 2,
      powerEffects: [{"type": "damage", "amount": 1, "to": "enemyHero", "spell": false}],
      phaseEffects: [{"type": "armor", "amount": 5}, {"type": "buff", "attack": 1, "health": 1, "to": "friendlyMinions"}],
      portraitId: "mirrornahira",
      forHero: "mage",
    },
    {
      id: "mirrorfrederia",
      name: "镜中的菲德莉亚",
      title: "另一边的背誓骑士",
      en: "THE MIRRORED OATHBREAKER",
      art: "knight",
      palette: "void",
      discoverClass: "mage",
      hp: 38,
      power: "倒映征召",
      quote: "盾面上的徽记我还留着。你呢？你刮掉的那一块，去哪了？",
      deck: ["squire", "guard", "oracle", "cleric", "golem", "treant", "paladin", "titan", "muster", "dawnvow", "sunblade", "absolution", "blessing", "shield", "solaris", "colossus", "dragon"],
      color: "#6f8f9a",
      powerCost: 2,
      powerEffects: [{"type": "summon", "card": "recruit", "count": 1, "requireSpace": true}],
      phaseEffects: [{"type": "armor", "amount": 5}, {"type": "buff", "attack": 1, "health": 1, "to": "friendlyMinions"}],
      portraitId: "mirrorfrederia",
      forHero: "paladin",
    },
    {
      id: "mirrorrowan",
      name: "镜中的罗温",
      title: "另一边的守林人",
      en: "THE MIRRORED WOODSMAN",
      art: "archer",
      palette: "void",
      discoverClass: "mage",
      hp: 38,
      power: "倒映穿心箭",
      quote: "同一座山，我先动的手。你看，树桩是新的。",
      deck: ["wolf", "moonfox", "spider", "duskstag", "rider", "huntress", "oracle", "wolves", "mooncall", "huntinghorn", "tracking", "dagger", "moonlance", "lifedrain", "stillness"],
      color: "#5f8f78",
      powerCost: 2,
      powerEffects: [{"type": "damage", "amount": 2, "to": "enemyHero", "spell": false}],
      phaseEffects: [{"type": "armor", "amount": 5}, {"type": "buff", "attack": 1, "health": 1, "to": "friendlyMinions"}],
      portraitId: "mirrorrowan",
      forHero: "ranger",
    },
    {
      id: "mirrorliol",
      name: "镜中的利奥尔",
      title: "另一边的提灯人",
      en: "THE MIRRORED LAMPLIGHTER",
      art: "mage",
      palette: "void",
      discoverClass: "mage",
      hp: 38,
      power: "倒映灯火",
      quote: "（灯里没有火。他提着它，像提着一只空的杯子。）",
      deck: ["wolf", "moonfox", "guard", "oracle", "soulguide", "duskstag", "leech", "necromancer", "graveoffering", "mooncall", "soultether", "moonlance", "lifedrain", "reaper", "stillness"],
      color: "#8a6fc4",
      powerCost: 2,
      powerEffects: [{"type": "draw", "count": 1}],
      phaseEffects: [{"type": "armor", "amount": 5}, {"type": "buff", "attack": 1, "health": 1, "to": "friendlyMinions"}],
      portraitId: "mirrorliol",
      forHero: "morla",
    },
    {
      id: "eve",
      name: "伊芙",
      title: "另一边的伊芙",
      en: "EVE OF THE OTHER SIDE",
      art: "treant",
      palette: "nature",
      discoverClass: "mage",
      hp: 62,
      power: "养花",
      quote: "它开的是黑色的花。没关系，花就是花。你先坐下，把手洗一洗。",
      deck: ["guard", "cleric", "treant", "golem", "titan", "archbishop", "colossus", "dragon", "bonelord", "solaris", "consecrate", "renew", "absolution", "icebarrier", "frostking", "blackbloom"],
      color: "#2f3a35",
      powerCost: 2,
      powerEffects: [{"type": "heal", "amount": 3}, {"type": "armor", "amount": 2}],
      phaseEffects: [{"type": "summon", "card": "thorn", "count": 2}, {"type": "armor", "amount": 10}, {"type": "heal", "amount": 10}],
      portraitId: "eve",
    },
  ],
  relics: [
    {
      id: "heart",
      name: "酒馆铜壶",
      icon: "heart",
      maxHealth: 8,
      triggers: [
        {
          event: "friendlyDeath",
          maxPerTurn: 1,
          effects: [
            {
              type: "heal",
              amount: 1,
            },
          ],
        },
      ],
    },
    {
      id: "lens",
      name: "校准的压力表",
      icon: "orb",
      spellDamage: 1,
      triggers: [
        {
          event: "spellCast",
          maxPerTurn: 1,
          effects: [
            {
              type: "armor",
              amount: 1,
            },
          ],
        },
      ],
    },
    {
      id: "crown",
      name: "凹痕矿工帽",
      icon: "sigil",
      onStart: [
        {
          type: "armor",
          amount: 7,
        },
      ],
    },
    {
      id: "feather",
      name: "矿区急救箱",
      icon: "raven",
      onTurn: [
        {
          type: "heal",
          amount: 2,
        },
      ],
    },
    {
      id: "ember",
      name: "火种护符",
      icon: "bolt",
      startingMana: 1,
    },
    {
      id: "banner",
      name: "工会的旧旗",
      icon: "banner",
      onStart: [
        {
          type: "summon",
          card: "squire",
          count: 1,
        },
      ],
      triggers: [
        {
          event: "shieldLost",
          maxPerTurn: 1,
          effects: [
            {
              type: "draw",
              count: 1,
            },
          ],
        },
      ],
    },
    // keepsakes of the descent: what a named opponent leaves, or what an event gives (content/story.js)
    { id: "whistle", name: "监工的铜哨", icon: "banner", onStart: [{ type: "summon", card: "guard", count: 1 }] },
    { id: "scale", name: "估价人的天平", icon: "sigil", bounty: 10 },
    { id: "icekey", name: "守根人的冰钥", icon: "orb", maxHealth: 5, triggers: [{ event: "turnEnd", maxPerTurn: 1, effects: [{ type: "armor", amount: 1 }] }] },
    { id: "rootsap", name: "根母的嫩枝", icon: "heart", onStart: [{ type: "summon", card: "thorn", count: 2 }] },
    { id: "lampwick", name: "守灯兽的灯芯", icon: "raven", maxHealth: 4, onTurn: [{ type: "heal", amount: 1 }] },
    { id: "wrench", name: "艾达的扳手", icon: "sigil", onTurn: [{ type: "armor", amount: 1 }] },
    { id: "watch", name: "停走的怀表", icon: "orb", onStart: [{ type: "draw", count: 1 }, { type: "armor", amount: 4 }] },
    { id: "canary", name: "井下的金丝雀", icon: "raven", triggers: [{ event: "friendlyDeath", maxPerTurn: 1, effects: [{ type: "armor", amount: 2 }] }] },
    // blessings: a relic for one battle only (the run hands them to the next battle and then lets them go); never a
    // treasure. `like` names the relic whose picture it borrows.
    { id: "b_vigil", name: "守夜的祝福", icon: "sigil", boon: true, like: "crown", onStart: [{ type: "armor", amount: 6 }] },
    { id: "b_escort", name: "矿工的掩护", icon: "banner", boon: true, like: "banner", onStart: [{ type: "summon", card: "guard", count: 1 }] },
    { id: "b_clockwork", name: "下了班的发条兵", icon: "sigil", boon: true, like: "lens", onStart: [{ type: "summon", card: "golem", count: 1 }] },
    { id: "b_warm", name: "一点余温", icon: "bolt", boon: true, like: "ember", onStart: [{ type: "draw", count: 1 }] },
    { id: "b_resin", name: "树脂护身", icon: "heart", boon: true, like: "heart", maxHealth: 6 },
  ],
  kw: {
    taunt: "嘲讽",
    shield: "圣盾",
    rush: "突袭",
    charge: "冲锋",
    lifesteal: "吸血",
    poison: "剧毒",
    windfury: "风怒",
    stealth: "潜行",
    reborn: "复生",
    spellpower: "法术伤害 +1",
  },
  archetypes: [
    {
      id: "mage_burn",
      hero: "mage",
      classId: "mage",
      name: "星火连奏",
      person: "炉前学徒",
      portraitId: "apprentice",
      plan: "保住施法核心，低费法术连续触发，直伤完成斩杀。",
      deck: [
        "spark",
        "spark",
        "wisp",
        "wisp",
        "oracle",
        "oracle",
        "guard",
        "guard",
        "sentinel",
        "sentinel",
        "phoenix",
        "phoenix",
        "rider",
        "rider",
        "bolt",
        "bolt",
        "frostbolt",
        "frostbolt",
        "fireball",
        "fireball",
        "wisdom",
        "wisdom",
        "nova",
        "nova",
        "dragon",
        "counterspell",
        "nyx",
        "dragon",
        "golem",
        "golem",
      ],
      strategy: "pressure",
    },
    {
      id: "mage_frost",
      hero: "mage",
      classId: "mage",
      name: "永冬秘法",
      person: "冰窖管事",
      portraitId: "icekeeper",
      plan: "用冻结和奥秘争取回合，补充手牌，以高费随从终结。",
      deck: [
        "guard",
        "guard",
        "oracle",
        "oracle",
        "golem",
        "golem",
        "cleric",
        "cleric",
        "treant",
        "treant",
        "frostbolt",
        "frostbolt",
        "nova",
        "nova",
        "polymorph",
        "polymorph",
        "wisdom",
        "wisdom",
        "icebarrier",
        "icebarrier",
        "fireball",
        "fireball",
        "storm",
        "storm",
        "discovery",
        "discovery",
        "frostking",
        "nyx",
        "dragon",
        "dragon",
      ],
      strategy: "control",
    },
    {
      id: "paladin_swarm",
      hero: "paladin",
      classId: "paladin",
      name: "黎明军势",
      person: "民兵队长",
      portraitId: "militia",
      plan: "新兵铺场，圣盾保场，王者号令将小随从变成威胁。",
      deck: [
        "squire",
        "squire",
        "guard",
        "guard",
        "oracle",
        "oracle",
        "sentinel",
        "sentinel",
        "berserker",
        "berserker",
        "golem",
        "golem",
        "paladin",
        "paladin",
        "blessing",
        "blessing",
        "rally",
        "rally",
        "shield",
        "shield",
        "muster",
        "muster",
        "absolution",
        "absolution",
        "sunblade",
        "sunblade",
        "solaris",
        "cleric",
        "cleric",
        "titan",
      ],
      strategy: "pressure",
    },
    {
      id: "paladin_guard",
      hero: "paladin",
      classId: "paladin",
      name: "不落圣盾",
      person: "老卫兵",
      portraitId: "oldguard",
      plan: "嘲讽与圣盾保护生命，持续补牌和恢复，稳住场面后反攻。",
      deck: [
        "squire",
        "squire",
        "guard",
        "guard",
        "oracle",
        "oracle",
        "cleric",
        "cleric",
        "golem",
        "golem",
        "treant",
        "treant",
        "paladin",
        "paladin",
        "titan",
        "titan",
        "muster",
        "renew",
        "muster",
        "sunblade",
        "absolution",
        "absolution",
        "blessing",
        "blessing",
        "shield",
        "shield",
        "solaris",
        "colossus",
        "colossus",
        "dragon",
      ],
      strategy: "control",
    },
    {
      id: "ranger_pack",
      hero: "ranger",
      classId: "ranger",
      name: "月影群猎",
      person: "林地猎人",
      portraitId: "woodswoman",
      plan: "野兽与武器争夺节奏，追踪补给，冲锋随从与穿心箭收尾。",
      deck: [
        "wolf",
        "wolf",
        "archer",
        "archer",
        "spider",
        "spider",
        "sentinel",
        "sentinel",
        "oracle",
        "oracle",
        "assassin",
        "assassin",
        "rider",
        "rider",
        "huntress",
        "huntress",
        "wolves",
        "wolves",
        "dagger",
        "dagger",
        "tracking",
        "tracking",
        "battlecry",
        "battlecry",
        "lifedrain",
        "lifedrain",
        "reaper",
        "reaper",
        "leech",
        "leech",
      ],
      strategy: "pressure",
    },
    {
      id: "ranger_death",
      hero: "ranger",
      classId: "ranger",
      name: "亡者回响",
      person: "掘墓人",
      portraitId: "gravedigger",
      plan: "亡语随从交换，织梦师补牌，血月行者成长，再用突袭夺回场面。",
      deck: [
        "wolf",
        "wolf",
        "guard",
        "guard",
        "oracle",
        "oracle",
        "golem",
        "golem",
        "leech",
        "leech",
        "necromancer",
        "necromancer",
        "reaper",
        "reaper",
        "titan",
        "titan",
        "assassin",
        "assassin",
        "lifedrain",
        "lifedrain",
        "execute",
        "execute",
        "dagger",
        "dagger",
        "tracking",
        "tracking",
        "sabotage",
        "sabotage",
        "colossus",
        "colossus",
      ],
      strategy: "control",
    },
    {
      id: "moon_covenant",
      hero: "morla",
      classId: "ranger",
      name: "月影神契",
      person: "月神殿修士",
      portraitId: "moonmonk",
      plan: "不同名称的非衍生随从死亡留下印记。先用献祭补牌，再选择防守、解场或积攒神祇降临。",
      strategy: "control",
      deck: [
        "wolf",
        "wolf",
        "moonfox",
        "moonfox",
        "guard",
        "guard",
        "oracle",
        "oracle",
        "soulguide",
        "soulguide",
        "duskstag",
        "duskstag",
        "leech",
        "leech",
        "necromancer",
        "necromancer",
        "graveoffering",
        "graveoffering",
        "mooncall",
        "mooncall",
        "soultether",
        "soultether",
        "moonlance",
        "moonlance",
        "lifedrain",
        "lifedrain",
        "reaper",
        "reaper",
        "stillness",
        "stillness",
      ],
    },
    {
      id: "moon_hunt",
      hero: "ranger",
      classId: "ranger",
      name: "契兽群猎",
      person: "驯兽人",
      portraitId: "beasttamer",
      plan: "野兽抢占场面，契鹿与灵狐支撑交换；使用狼王破阵，保留守灯巨兽应对抢攻。",
      strategy: "pressure",
      deck: [
        "wolf",
        "wolf",
        "moonfox",
        "moonfox",
        "archer",
        "archer",
        "spider",
        "spider",
        "sentinel",
        "sentinel",
        "duskstag",
        "duskstag",
        "rider",
        "rider",
        "huntress",
        "huntress",
        "mooncall",
        "mooncall",
        "tracking",
        "tracking",
        "dagger",
        "dagger",
        "battlecry",
        "battlecry",
        "moonlance",
        "moonlance",
        "lifedrain",
        "lifedrain",
        "sabotage",
        "sabotage",
      ],
    },
    {
      id: "pantheon_stars",
      hero: "mage",
      classId: "mage",
      name: "星焰天仪",
      person: "天文台学者",
      portraitId: "stargazer",
      plan: "成功施放六种非衍生法术唤醒群星的园丁；织火补牌、寒霜控场，九费降临后保留法术压制随从。",
      strategy: "control",
      deck: [
        "guard",
        "guard",
        "oracle",
        "oracle",
        "golem",
        "golem",
        "cleric",
        "cleric",
        "treant",
        "treant",
        "frostbolt",
        "frostbolt",
        "nova",
        "nova",
        "polymorph",
        "polymorph",
        "wisdom",
        "wisdom",
        "icebarrier",
        "icebarrier",
        "fireball",
        "fireball",
        "storm",
        "storm",
        "discovery",
        "discovery",
        "frostking",
        "nyx",
        "starweave",
        "starweave",
      ],
    },
    {
      id: "pantheon_dawn",
      hero: "paladin",
      classId: "paladin",
      name: "曙日誓军",
      person: "教会卫士",
      portraitId: "churchguard",
      plan: "让圣盾在敌方攻击与法术中守护军团，四次破盾后唤醒执盾者。晨光守誓补盾，保留反击场面。",
      strategy: "control",
      deck: [
        "squire",
        "squire",
        "guard",
        "guard",
        "oracle",
        "oracle",
        "cleric",
        "cleric",
        "golem",
        "golem",
        "treant",
        "treant",
        "paladin",
        "paladin",
        "titan",
        "titan",
        "muster",
        "dawnvow",
        "muster",
        "sunblade",
        "absolution",
        "absolution",
        "blessing",
        "blessing",
        "shield",
        "shield",
        "solaris",
        "dawnvow",
        "colossus",
        "dragon",
      ],
    },
    {
      id: "pantheon_hunt",
      hero: "ranger",
      classId: "ranger",
      name: "白角之路",
      person: "山村猎手",
      portraitId: "villagehunter",
      plan: "野兽主动攻击敌方随从积累六次狩猎，每回合最多两次。猎号补给；白角率领突袭灵狼夺回场面。",
      strategy: "pressure",
      deck: [
        "wolf",
        "wolf",
        "moonfox",
        "moonfox",
        "spider",
        "spider",
        "duskstag",
        "duskstag",
        "rider",
        "rider",
        "huntress",
        "huntress",
        "oracle",
        "oracle",
        "wolves",
        "wolves",
        "mooncall",
        "mooncall",
        "huntinghorn",
        "huntinghorn",
        "tracking",
        "tracking",
        "dagger",
        "dagger",
        "moonlance",
        "moonlance",
        "lifedrain",
        "lifedrain",
        "stillness",
        "stillness",
      ],
    },
  ],
};
if (typeof module !== "undefined") module.exports = EmberCampaign;
