/* Authored campaign and archetypes. */
const EmberCampaign = {
  classes: [
    {
      id: "neutral",
      name: "中立",
    },
    {
      id: "mage",
      name: "法师",
    },
    {
      id: "paladin",
      name: "圣卫",
    },
    {
      id: "ranger",
      name: "游侠",
    },
  ],
  tribes: [
    {
      id: "beast",
      name: "野兽",
    },
    {
      id: "undead",
      name: "亡灵",
    },
    {
      id: "dragon",
      name: "龙",
    },
  ],
  deckRules: {
    size: 30,
    maxCopies: 2,
    rarityCopies: {
      legendary: 1,
    },
  },
  heroes: [
    {
      id: "mage",
      classId: "mage",
      powerIcon: "fire",
      name: "星焰法师",
      title: "艾莉娅",
      sub: "ARCANE & EMBER",
      art: "mage",
      palette: "arcane",
      power: "星火",
      target: "enemy",
      desc: "以烈焰与寒霜掌控战局，用法术完成致命一击。",
      defaultDeckId: "pantheon_stars",
      powerCost: 2,
      powerEffects: [
        {
          type: "damage",
          amount: 1,
          to: "selected",
          spell: false,
        },
      ],
      portraitId: "oracle",
      defaultContracts: ["jingchen"],
    },
    {
      id: "paladin",
      classId: "paladin",
      powerIcon: "shield",
      name: "黎明圣卫",
      title: "雷昂",
      sub: "LIGHT & HONOR",
      art: "knight",
      palette: "gold",
      power: "征召",
      desc: "坚守誓约，集结圣盾军团，在号角声中反击。",
      defaultDeckId: "pantheon_dawn",
      powerCost: 2,
      powerEffects: [
        {
          type: "summon",
          card: "recruit",
          count: 1,
          requireSpace: true,
        },
      ],
      portraitId: "paladin",
      defaultContracts: ["aurion"],
    },
    {
      id: "ranger",
      classId: "ranger",
      powerIcon: "sword",
      name: "暗影游侠",
      title: "薇丝珀",
      sub: "WILD & SHADOW",
      art: "archer",
      palette: "nature",
      power: "穿心箭",
      desc: "驾驭野兽与暗影，利用突袭和武器夺取先机。",
      defaultDeckId: "pantheon_hunt",
      powerCost: 2,
      powerEffects: [
        {
          type: "damage",
          amount: 2,
          to: "enemyHero",
          spell: false,
        },
      ],
      portraitId: "archer",
      defaultContracts: ["eclipsewolf", "moonguard", "fenlos"],
    },
    {
      id: "morla",
      classId: "ranger",
      powerIcon: "raven",
      name: "送魂人",
      title: "莫菈",
      sub: "MOON & MEMORY",
      art: "mage",
      palette: "void",
      power: "送魂灯",
      target: "friendlyMinion",
      desc: "以献祭兑现亡语，收集灵魂印记，唤醒冥月契约。",
      defaultDeckId: "moon_covenant",
      powerCost: 2,
      powerEffects: [
        {
          type: "sacrifice",
          to: "selected",
        },
        {
          type: "draw",
          count: 1,
        },
      ],
      portraitId: "soulguide",
      defaultContracts: ["eclipsewolf", "moonguard", "selmyra"],
    },
  ],
  bosses: [
    {
      id: "warden",
      name: "灰烬监守",
      title: "余火之门",
      en: "THE ASHEN WARDEN",
      art: "knight",
      palette: "ember",
      discoverClass: "mage",
      hp: 30,
      power: "余烬之怒",
      quote: "每一簇反抗的火焰，都将在此熄灭。",
      deck: [
        "squire",
        "spark",
        "guard",
        "sentinel",
        "bolt",
        "golem",
        "berserker",
        "cleric",
        "fireball",
        "phoenix",
        "titan",
        "dragon",
        "wisdom",
        "dagger",
        "shield",
      ],
      color: "#d47742",
      powerCost: 2,
      powerEffects: [
        {
          type: "damage",
          amount: 1,
          to: "enemyHero",
          spell: false,
        },
      ],
      phaseEffects: [
        {
          type: "armor",
          amount: 3,
        },
        {
          type: "summon",
          card: "guard",
          count: 1,
        },
      ],
      portraitId: "berserker",
    },
    {
      id: "queen",
      name: "荆棘女王",
      title: "低语密林",
      en: "THE THORN QUEEN",
      art: "treant",
      palette: "nature",
      discoverClass: "mage",
      hp: 34,
      power: "蔓生",
      quote: "听见了吗？树根正在呼唤你的名字。",
      deck: [
        "wolf",
        "archer",
        "spider",
        "guard",
        "treant",
        "wolves",
        "blessing",
        "rally",
        "muster",
        "golem",
        "oracle",
        "huntress",
        "tracking",
        "absolution",
        "sentinel",
      ],
      color: "#8bb773",
      powerCost: 2,
      powerEffects: [
        {
          type: "summon",
          card: "thorn",
          count: 1,
          requireSpace: true,
        },
      ],
      phaseEffects: [
        {
          type: "buff",
          attack: 1,
          health: 2,
          to: "friendlyMinions",
        },
      ],
      portraitId: "treant",
    },
    {
      id: "oracle",
      name: "深渊先知",
      title: "无光圣所",
      en: "THE ABYSSAL ORACLE",
      art: "mage",
      palette: "void",
      discoverClass: "mage",
      hp: 36,
      power: "灵魂汲取",
      quote: "你所看见的终点，不过是我的序章。",
      deck: [
        "leech",
        "assassin",
        "oracle",
        "wisp",
        "necromancer",
        "reaper",
        "lifedrain",
        "execute",
        "discovery",
        "counterspell",
        "silence",
        "wisdom",
        "wolf",
        "guard",
        "nyx",
      ],
      color: "#a889d1",
      powerCost: 2,
      powerEffects: [
        {
          type: "damage",
          amount: 1,
          to: "enemyHero",
          spell: false,
        },
        {
          type: "heal",
          amount: 2,
        },
      ],
      phaseEffects: [
        {
          type: "summon",
          card: "leech",
          count: 2,
        },
      ],
      portraitId: "necromancer",
    },
    {
      id: "frost",
      name: "霜狱君王",
      title: "永冻王座",
      en: "THE FROSTBOUND KING",
      art: "reaper",
      palette: "ice",
      discoverClass: "mage",
      hp: 40,
      power: "凛冬触碰",
      quote: "时间在此凝结，希望也不例外。",
      deck: [
        "squire",
        "guard",
        "golem",
        "rider",
        "frostbolt",
        "nova",
        "oracle",
        "paladin",
        "titan",
        "frostking",
        "icebarrier",
        "wisdom",
        "polymorph",
        "renew",
        "sentinel",
      ],
      color: "#79c9d9",
      powerCost: 2,
      powerEffects: [
        {
          type: "randomDamageFreeze",
          amount: 1,
        },
      ],
      phaseEffects: [
        {
          type: "armor",
          amount: 8,
        },
        {
          type: "freeze",
          to: "enemyMinions",
        },
      ],
      portraitId: "frostking",
    },
    {
      id: "dragon",
      name: "终焉巨龙",
      title: "世界之烬",
      en: "THE WORLD ENDER",
      art: "dragon",
      palette: "blood",
      discoverClass: "mage",
      hp: 45,
      power: "焚界吐息",
      quote: "在最后一颗星辰熄灭之前，燃烧吧。",
      deck: [
        "spark",
        "guard",
        "sentinel",
        "bolt",
        "berserker",
        "golem",
        "phoenix",
        "rider",
        "fireball",
        "dragon",
        "ashdragon",
        "titan",
        "paladin",
        "storm",
        "renew",
      ],
      color: "#df7059",
      powerCost: 3,
      powerEffects: [
        {
          type: "damage",
          amount: 1,
          to: "enemies",
          spell: false,
        },
      ],
      phaseEffects: [
        {
          type: "damage",
          amount: 2,
          to: "enemies",
          spell: false,
        },
        {
          type: "summon",
          card: "dragon",
          count: 1,
        },
      ],
      portraitId: "ashdragon",
    },
    {
      id: "moonkeeper",
      name: "断契监誓者",
      title: "月蚀祭坛",
      en: "THE COVENANT KEEPER",
      art: "mage",
      palette: "void",
      discoverClass: "mage",
      hp: 40,
      power: "封契之刃",
      quote: "神明记得每一次牺牲。你，付得起代价吗？",
      deck: [
        "guard",
        "oracle",
        "sentinel",
        "moonfox",
        "duskstag",
        "soulguide",
        "stillness",
        "polymorph",
        "moonlance",
        "necromancer",
        "lifedrain",
        "reaper",
        "titan",
        "wisdom",
        "silence",
      ],
      color: "#a889d1",
      powerCost: 3,
      powerEffects: [
        {
          type: "randomDamageFreeze",
          amount: 2,
        },
      ],
      phaseEffects: [
        {
          type: "summon",
          card: "moonguard",
          count: 1,
        },
      ],
      portraitId: "moonguard",
    },
  ],
  relics: [
    {
      id: "heart",
      name: "不熄之心",
      icon: "heart",
      maxHealth: 8,
      triggers: [
        {
          event: "friendlyDeath",
          maxPerTurn: 1,
          effects: [
            {
              type: "heal",
              amount: 1,
            },
          ],
        },
      ],
    },
    {
      id: "lens",
      name: "星界透镜",
      icon: "orb",
      spellDamage: 1,
      triggers: [
        {
          event: "spellCast",
          maxPerTurn: 1,
          effects: [
            {
              type: "armor",
              amount: 1,
            },
          ],
        },
      ],
    },
    {
      id: "crown",
      name: "晨曦王冠",
      icon: "sigil",
      onStart: [
        {
          type: "armor",
          amount: 7,
        },
      ],
    },
    {
      id: "feather",
      name: "渡鸦之羽",
      icon: "raven",
      onTurn: [
        {
          type: "heal",
          amount: 2,
        },
      ],
    },
    {
      id: "ember",
      name: "初火余烬",
      icon: "bolt",
      startingMana: 1,
    },
    {
      id: "banner",
      name: "誓约战旗",
      icon: "banner",
      onStart: [
        {
          type: "summon",
          card: "squire",
          count: 1,
        },
      ],
      triggers: [
        {
          event: "shieldLost",
          maxPerTurn: 1,
          effects: [
            {
              type: "draw",
              count: 1,
            },
          ],
        },
      ],
    },
  ],
  kw: {
    taunt: "嘲讽",
    shield: "圣盾",
    rush: "突袭",
    charge: "冲锋",
    lifesteal: "吸血",
    poison: "剧毒",
    windfury: "风怒",
    stealth: "潜行",
    reborn: "复生",
    spellpower: "法术伤害 +1",
  },
  archetypes: [
    {
      id: "mage_burn",
      hero: "mage",
      classId: "mage",
      name: "星火连奏",
      plan: "保住施法核心，低费法术连续触发，直伤完成斩杀。",
      deck: [
        "spark",
        "spark",
        "wisp",
        "wisp",
        "oracle",
        "oracle",
        "guard",
        "guard",
        "sentinel",
        "sentinel",
        "phoenix",
        "phoenix",
        "rider",
        "rider",
        "bolt",
        "bolt",
        "frostbolt",
        "frostbolt",
        "fireball",
        "fireball",
        "wisdom",
        "wisdom",
        "nova",
        "nova",
        "dragon",
        "counterspell",
        "nyx",
        "dragon",
        "golem",
        "golem",
      ],
      strategy: "pressure",
    },
    {
      id: "mage_frost",
      hero: "mage",
      classId: "mage",
      name: "永冬秘法",
      plan: "用冻结和奥秘争取回合，补充手牌，以高费随从终结。",
      deck: [
        "guard",
        "guard",
        "oracle",
        "oracle",
        "golem",
        "golem",
        "cleric",
        "cleric",
        "treant",
        "treant",
        "frostbolt",
        "frostbolt",
        "nova",
        "nova",
        "polymorph",
        "polymorph",
        "wisdom",
        "wisdom",
        "icebarrier",
        "icebarrier",
        "fireball",
        "fireball",
        "storm",
        "storm",
        "discovery",
        "discovery",
        "frostking",
        "nyx",
        "dragon",
        "dragon",
      ],
      strategy: "control",
    },
    {
      id: "paladin_swarm",
      hero: "paladin",
      classId: "paladin",
      name: "黎明军势",
      plan: "新兵铺场，圣盾保场，王者号令将小随从变成威胁。",
      deck: [
        "squire",
        "squire",
        "guard",
        "guard",
        "oracle",
        "oracle",
        "sentinel",
        "sentinel",
        "berserker",
        "berserker",
        "golem",
        "golem",
        "paladin",
        "paladin",
        "blessing",
        "blessing",
        "rally",
        "rally",
        "shield",
        "shield",
        "muster",
        "muster",
        "absolution",
        "absolution",
        "sunblade",
        "sunblade",
        "solaris",
        "cleric",
        "cleric",
        "titan",
      ],
      strategy: "pressure",
    },
    {
      id: "paladin_guard",
      hero: "paladin",
      classId: "paladin",
      name: "不落圣盾",
      plan: "嘲讽与圣盾保护生命，持续补牌和恢复，稳住场面后反攻。",
      deck: [
        "squire",
        "squire",
        "guard",
        "guard",
        "oracle",
        "oracle",
        "cleric",
        "cleric",
        "golem",
        "golem",
        "treant",
        "treant",
        "paladin",
        "paladin",
        "titan",
        "titan",
        "muster",
        "renew",
        "muster",
        "sunblade",
        "absolution",
        "absolution",
        "blessing",
        "blessing",
        "shield",
        "shield",
        "solaris",
        "colossus",
        "colossus",
        "dragon",
      ],
      strategy: "control",
    },
    {
      id: "ranger_pack",
      hero: "ranger",
      classId: "ranger",
      name: "月影群猎",
      plan: "野兽与武器争夺节奏，追踪补给，冲锋随从与穿心箭收尾。",
      deck: [
        "wolf",
        "wolf",
        "archer",
        "archer",
        "spider",
        "spider",
        "sentinel",
        "sentinel",
        "oracle",
        "oracle",
        "assassin",
        "assassin",
        "rider",
        "rider",
        "huntress",
        "huntress",
        "wolves",
        "wolves",
        "dagger",
        "dagger",
        "tracking",
        "tracking",
        "battlecry",
        "battlecry",
        "lifedrain",
        "lifedrain",
        "reaper",
        "reaper",
        "leech",
        "leech",
      ],
      strategy: "pressure",
    },
    {
      id: "ranger_death",
      hero: "ranger",
      classId: "ranger",
      name: "亡者回响",
      plan: "亡语随从交换，织梦师补牌，血月行者成长，再用突袭夺回场面。",
      deck: [
        "wolf",
        "wolf",
        "guard",
        "guard",
        "oracle",
        "oracle",
        "golem",
        "golem",
        "leech",
        "leech",
        "necromancer",
        "necromancer",
        "reaper",
        "reaper",
        "titan",
        "titan",
        "assassin",
        "assassin",
        "lifedrain",
        "lifedrain",
        "execute",
        "execute",
        "dagger",
        "dagger",
        "tracking",
        "tracking",
        "sabotage",
        "sabotage",
        "colossus",
        "colossus",
      ],
      strategy: "control",
    },
    {
      id: "moon_covenant",
      hero: "morla",
      classId: "ranger",
      name: "月影神契",
      plan: "不同名称的非衍生随从死亡留下印记。先用献祭补牌，再选择防守、解场或积攒神祇降临。",
      strategy: "control",
      deck: [
        "wolf",
        "wolf",
        "moonfox",
        "moonfox",
        "guard",
        "guard",
        "oracle",
        "oracle",
        "soulguide",
        "soulguide",
        "duskstag",
        "duskstag",
        "leech",
        "leech",
        "necromancer",
        "necromancer",
        "graveoffering",
        "graveoffering",
        "mooncall",
        "mooncall",
        "soultether",
        "soultether",
        "moonlance",
        "moonlance",
        "lifedrain",
        "lifedrain",
        "reaper",
        "reaper",
        "stillness",
        "stillness",
      ],
    },
    {
      id: "moon_hunt",
      hero: "ranger",
      classId: "ranger",
      name: "契兽群猎",
      plan: "野兽抢占场面，契鹿与灵狐支撑交换；使用狼王破阵，保留守灯巨兽应对抢攻。",
      strategy: "pressure",
      deck: [
        "wolf",
        "wolf",
        "moonfox",
        "moonfox",
        "archer",
        "archer",
        "spider",
        "spider",
        "sentinel",
        "sentinel",
        "duskstag",
        "duskstag",
        "rider",
        "rider",
        "huntress",
        "huntress",
        "mooncall",
        "mooncall",
        "tracking",
        "tracking",
        "dagger",
        "dagger",
        "battlecry",
        "battlecry",
        "moonlance",
        "moonlance",
        "lifedrain",
        "lifedrain",
        "sabotage",
        "sabotage",
      ],
    },
    {
      id: "pantheon_stars",
      hero: "mage",
      classId: "mage",
      name: "星焰天仪",
      plan: "成功施放六种非衍生法术唤醒星焰神；织火补牌、寒霜控场，九费降临后保留法术压制随从。",
      strategy: "control",
      deck: [
        "guard",
        "guard",
        "oracle",
        "oracle",
        "golem",
        "golem",
        "cleric",
        "cleric",
        "treant",
        "treant",
        "frostbolt",
        "frostbolt",
        "nova",
        "nova",
        "polymorph",
        "polymorph",
        "wisdom",
        "wisdom",
        "icebarrier",
        "icebarrier",
        "fireball",
        "fireball",
        "storm",
        "storm",
        "discovery",
        "discovery",
        "frostking",
        "nyx",
        "starweave",
        "starweave",
      ],
    },
    {
      id: "pantheon_dawn",
      hero: "paladin",
      classId: "paladin",
      name: "曙日誓军",
      plan: "让圣盾在敌方攻击与法术中守护军团，四次破盾后唤醒曙日神。晨光守誓补盾，保留反击场面。",
      strategy: "control",
      deck: [
        "squire",
        "squire",
        "guard",
        "guard",
        "oracle",
        "oracle",
        "cleric",
        "cleric",
        "golem",
        "golem",
        "treant",
        "treant",
        "paladin",
        "paladin",
        "titan",
        "titan",
        "muster",
        "dawnvow",
        "muster",
        "sunblade",
        "absolution",
        "absolution",
        "blessing",
        "blessing",
        "shield",
        "shield",
        "solaris",
        "dawnvow",
        "colossus",
        "dragon",
      ],
    },
    {
      id: "pantheon_hunt",
      hero: "ranger",
      classId: "ranger",
      name: "荒猎神途",
      plan: "野兽主动攻击敌方随从积累六次狩猎，每回合最多两次。猎号补给；荒猎神率领突袭灵狼夺回场面。",
      strategy: "pressure",
      deck: [
        "wolf",
        "wolf",
        "moonfox",
        "moonfox",
        "spider",
        "spider",
        "duskstag",
        "duskstag",
        "rider",
        "rider",
        "huntress",
        "huntress",
        "oracle",
        "oracle",
        "wolves",
        "wolves",
        "mooncall",
        "mooncall",
        "huntinghorn",
        "huntinghorn",
        "tracking",
        "tracking",
        "dagger",
        "dagger",
        "moonlance",
        "moonlance",
        "lifedrain",
        "lifedrain",
        "stillness",
        "stillness",
      ],
    },
  ],
};
if (typeof module !== "undefined") module.exports = EmberCampaign;
