/* Authored card definitions. Text is derived from effects by EmberRules. */
const EmberCardDefinitions = [
  {
    id: "spark",
    name: "引火学徒",
    cost: 1,
    atk: 1,
    hp: 3,
    art: "mage",
    palette: "ember",
    rarity: "common",
    type: "minion",
    onPlay: [
      {
        type: "damage",
        amount: 1,
        to: "enemyHero",
        spell: false,
      },
    ],
  },
  {
    id: "squire",
    name: "晨曦侍从",
    cost: 1,
    atk: 1,
    hp: 2,
    art: "knight",
    palette: "gold",
    rarity: "common",
    type: "minion",
    tags: ["shield"],
  },
  {
    id: "wolf",
    name: "月影幼狼",
    cost: 1,
    atk: 2,
    hp: 1,
    art: "wolf",
    palette: "ice",
    rarity: "common",
    type: "minion",
    onDeath: [
      {
        type: "summon",
        card: "pup",
        count: 1,
      },
    ],
  },
  {
    id: "archer",
    name: "边境游侠",
    cost: 1,
    atk: 2,
    hp: 1,
    art: "archer",
    palette: "nature",
    rarity: "common",
    type: "minion",
    target: "enemyMinion",
    onPlay: [
      {
        type: "damage",
        amount: 1,
        to: "selected",
        spell: false,
      },
    ],
  },
  {
    id: "guard",
    name: "铁誓卫士",
    cost: 2,
    atk: 2,
    hp: 3,
    art: "knight",
    palette: "steel",
    rarity: "common",
    type: "minion",
    tags: ["taunt"],
  },
  {
    id: "oracle",
    name: "星界观测者",
    cost: 2,
    atk: 2,
    hp: 2,
    art: "mage",
    palette: "arcane",
    rarity: "rare",
    type: "minion",
    onPlay: [
      {
        type: "draw",
        count: 1,
      },
    ],
  },
  {
    id: "wisp",
    name: "暮光精灵",
    cost: 2,
    atk: 3,
    hp: 2,
    art: "spirit",
    palette: "arcane",
    rarity: "rare",
    type: "minion",
    tags: ["spellpower"],
  },
  {
    id: "spider",
    name: "幽谷蛛后",
    cost: 2,
    atk: 1,
    hp: 3,
    art: "spider",
    palette: "nature",
    rarity: "rare",
    type: "minion",
    tags: ["poison"],
  },
  {
    id: "sentinel",
    name: "烬翼斥候",
    cost: 2,
    atk: 2,
    hp: 3,
    art: "raven",
    palette: "ember",
    rarity: "common",
    type: "minion",
    tags: ["rush"],
  },
  {
    id: "assassin",
    name: "夜幕刺客",
    cost: 3,
    atk: 4,
    hp: 2,
    art: "rogue",
    palette: "void",
    rarity: "rare",
    type: "minion",
    tags: ["stealth"],
  },
  {
    id: "cleric",
    name: "曙光祭司",
    cost: 3,
    atk: 3,
    hp: 3,
    art: "mage",
    palette: "gold",
    rarity: "common",
    type: "minion",
    onPlay: [
      {
        type: "heal",
        amount: 4,
      },
    ],
  },
  {
    id: "berserker",
    name: "赤岩狂战士",
    cost: 3,
    atk: 3,
    hp: 4,
    art: "knight",
    palette: "ember",
    rarity: "rare",
    type: "minion",
    tags: ["windfury"],
  },
  {
    id: "golem",
    name: "符文石像",
    cost: 3,
    atk: 2,
    hp: 5,
    art: "golem",
    palette: "ice",
    rarity: "rare",
    type: "minion",
    tags: ["taunt"],
    onDeath: [
      {
        type: "armor",
        amount: 3,
      },
    ],
  },
  {
    id: "leech",
    name: "血月行者",
    cost: 3,
    atk: 3,
    hp: 3,
    art: "rogue",
    palette: "blood",
    rarity: "rare",
    type: "minion",
    tags: ["lifesteal"],
  },
  {
    id: "treant",
    name: "古木守护者",
    cost: 4,
    atk: 3,
    hp: 6,
    art: "treant",
    palette: "nature",
    rarity: "common",
    type: "minion",
    tags: ["taunt"],
  },
  {
    id: "phoenix",
    name: "不灭凤凰",
    cost: 4,
    atk: 4,
    hp: 3,
    art: "phoenix",
    palette: "ember",
    rarity: "epic",
    type: "minion",
    tags: ["reborn"],
  },
  {
    id: "rider",
    name: "霜牙狼骑",
    cost: 4,
    atk: 4,
    hp: 4,
    art: "wolf",
    palette: "ice",
    rarity: "rare",
    type: "minion",
    tags: ["rush"],
  },
  {
    id: "necromancer",
    name: "亡者织梦师",
    cost: 4,
    atk: 3,
    hp: 4,
    art: "mage",
    palette: "void",
    rarity: "epic",
    type: "minion",
    onPlay: [
      {
        type: "summon",
        card: "skeleton",
        count: 2,
      },
    ],
  },
  {
    id: "paladin",
    name: "圣光裁决者",
    cost: 5,
    atk: 4,
    hp: 5,
    art: "knight",
    palette: "gold",
    rarity: "epic",
    type: "minion",
    tags: ["taunt", "shield"],
  },
  {
    id: "titan",
    name: "玄铁泰坦",
    cost: 5,
    atk: 5,
    hp: 6,
    art: "golem",
    palette: "steel",
    rarity: "rare",
    type: "minion",
    onDeath: [
      {
        type: "summon",
        card: "stone",
        count: 1,
      },
    ],
  },
  {
    id: "huntress",
    name: "荒野之矛",
    cost: 5,
    atk: 5,
    hp: 4,
    art: "archer",
    palette: "nature",
    rarity: "epic",
    type: "minion",
    tags: ["charge"],
  },
  {
    id: "dragon",
    name: "烬喉幼龙",
    cost: 6,
    atk: 6,
    hp: 6,
    art: "dragon",
    palette: "ember",
    rarity: "epic",
    type: "minion",
    onPlay: [
      {
        type: "damage",
        amount: 2,
        to: "enemyMinions",
        spell: false,
      },
    ],
  },
  {
    id: "reaper",
    name: "黯月收割者",
    cost: 6,
    atk: 5,
    hp: 5,
    art: "reaper",
    palette: "void",
    rarity: "epic",
    type: "minion",
    tags: ["lifesteal", "rush"],
  },
  {
    id: "colossus",
    name: "远古山岳",
    cost: 7,
    atk: 7,
    hp: 9,
    art: "golem",
    palette: "nature",
    rarity: "epic",
    type: "minion",
    tags: ["taunt"],
  },
  {
    id: "solaris",
    name: "逐日者·索拉",
    cost: 7,
    atk: 6,
    hp: 6,
    art: "knight",
    palette: "gold",
    rarity: "legendary",
    type: "minion",
    tags: ["shield"],
    onPlay: [
      {
        type: "buff",
        attack: 1,
        health: 1,
        to: "friendlyOthers",
      },
    ],
  },
  {
    id: "nyx",
    name: "星陨女王·妮克丝",
    cost: 8,
    atk: 6,
    hp: 8,
    art: "mage",
    palette: "arcane",
    rarity: "legendary",
    type: "minion",
    tags: ["spellpower"],
    onPlay: [
      {
        type: "draw",
        count: 2,
      },
    ],
  },
  {
    id: "ashdragon",
    name: "终焰·阿什拉",
    cost: 9,
    atk: 8,
    hp: 8,
    art: "dragon",
    palette: "ember",
    rarity: "legendary",
    type: "minion",
    onPlay: [
      {
        type: "damage",
        amount: 3,
        to: "allOthers",
        spell: false,
      },
    ],
  },
  {
    id: "frostking",
    name: "白霜之王",
    cost: 8,
    atk: 7,
    hp: 8,
    art: "reaper",
    palette: "ice",
    rarity: "legendary",
    type: "minion",
    tags: ["taunt"],
    onPlay: [
      {
        type: "freeze",
        to: "enemyMinions",
      },
    ],
  },
  {
    id: "bolt",
    name: "星火箭",
    cost: 1,
    art: "bolt",
    palette: "ember",
    rarity: "common",
    type: "spell",
    target: "enemy",
    onPlay: [
      {
        type: "damage",
        amount: 2,
        to: "selected",
        spell: true,
      },
    ],
  },
  {
    id: "frostbolt",
    name: "寒霜之触",
    cost: 2,
    art: "crystal",
    palette: "ice",
    rarity: "rare",
    type: "spell",
    target: "enemy",
    onPlay: [
      {
        type: "damage",
        amount: 3,
        to: "selected",
        spell: true,
      },
      {
        type: "freeze",
        to: "selected",
      },
    ],
  },
  {
    id: "fireball",
    name: "陨火术",
    cost: 4,
    art: "meteor",
    palette: "ember",
    rarity: "rare",
    type: "spell",
    target: "enemy",
    onPlay: [
      {
        type: "damage",
        amount: 6,
        to: "selected",
        spell: true,
      },
    ],
  },
  {
    id: "nova",
    name: "冰封领域",
    cost: 3,
    art: "crystal",
    palette: "ice",
    rarity: "rare",
    type: "spell",
    onPlay: [
      {
        type: "freeze",
        to: "enemyMinions",
      },
      {
        type: "draw",
        count: 1,
      },
    ],
  },
  {
    id: "storm",
    name: "烈焰风暴",
    cost: 7,
    art: "meteor",
    palette: "ember",
    rarity: "epic",
    type: "spell",
    onPlay: [
      {
        type: "damage",
        amount: 4,
        to: "enemyMinions",
        spell: true,
      },
    ],
  },
  {
    id: "wisdom",
    name: "星界密卷",
    cost: 3,
    art: "book",
    palette: "arcane",
    rarity: "common",
    type: "spell",
    onPlay: [
      {
        type: "draw",
        count: 2,
      },
    ],
  },
  {
    id: "blessing",
    name: "黎明祝福",
    cost: 2,
    art: "sigil",
    palette: "gold",
    rarity: "common",
    type: "spell",
    target: "friendlyMinion",
    onPlay: [
      {
        type: "buff",
        attack: 2,
        health: 2,
        to: "selected",
      },
    ],
  },
  {
    id: "renew",
    name: "生命之泉",
    cost: 2,
    art: "potion",
    palette: "nature",
    rarity: "common",
    type: "spell",
    onPlay: [
      {
        type: "heal",
        amount: 6,
      },
      {
        type: "draw",
        count: 1,
      },
    ],
  },
  {
    id: "execute",
    name: "暗影湮灭",
    cost: 5,
    art: "reaper",
    palette: "void",
    rarity: "epic",
    type: "spell",
    target: "enemyMinion",
    onPlay: [
      {
        type: "destroy",
        to: "selected",
      },
    ],
  },
  {
    id: "silence",
    name: "遗忘咒印",
    cost: 1,
    art: "sigil",
    palette: "void",
    rarity: "rare",
    type: "spell",
    target: "minion",
    onPlay: [
      {
        type: "silence",
        to: "selected",
      },
    ],
  },
  {
    id: "rally",
    name: "王者号令",
    cost: 4,
    art: "banner",
    palette: "gold",
    rarity: "epic",
    type: "spell",
    onPlay: [
      {
        type: "buff",
        attack: 2,
        health: 2,
        to: "friendlyMinions",
      },
    ],
  },
  {
    id: "wolves",
    name: "群狼呼唤",
    cost: 3,
    art: "wolf",
    palette: "nature",
    rarity: "rare",
    type: "spell",
    onPlay: [
      {
        type: "summon",
        card: "spiritwolf",
        count: 2,
        requireSpace: true,
      },
    ],
  },
  {
    id: "shield",
    name: "圣光庇佑",
    cost: 1,
    art: "sigil",
    palette: "gold",
    rarity: "common",
    type: "spell",
    target: "friendlyMinion",
    onPlay: [
      {
        type: "grant",
        tag: "shield",
        to: "selected",
      },
    ],
  },
  {
    id: "lifedrain",
    name: "灵魂虹吸",
    cost: 3,
    art: "orb",
    palette: "blood",
    rarity: "rare",
    type: "spell",
    target: "enemy",
    onPlay: [
      {
        type: "damage",
        amount: 3,
        to: "selected",
        spell: true,
      },
      {
        type: "heal",
        amount: 3,
      },
    ],
  },
  {
    id: "dagger",
    name: "银月双刃",
    cost: 2,
    atk: 2,
    hp: 2,
    art: "sword",
    palette: "steel",
    rarity: "rare",
    type: "weapon",
  },
  {
    id: "sunblade",
    name: "日耀圣剑",
    cost: 4,
    atk: 4,
    hp: 2,
    art: "sword",
    palette: "gold",
    rarity: "epic",
    type: "weapon",
    tags: ["lifesteal"],
  },
  {
    id: "polymorph",
    name: "迷途化形",
    cost: 4,
    art: "sheep",
    palette: "arcane",
    rarity: "rare",
    type: "spell",
    target: "enemyMinion",
    onPlay: [
      {
        type: "transform",
        card: "sheep",
        to: "selected",
      },
    ],
  },
  {
    id: "discovery",
    name: "虚空洞见",
    cost: 2,
    art: "orb",
    palette: "arcane",
    rarity: "epic",
    type: "spell",
    onPlay: [
      {
        type: "discover",
        count: 3,
        cardType: "spell",
      },
    ],
  },
  {
    id: "ambush",
    name: "镜像伏击",
    cost: 2,
    art: "mirror",
    palette: "arcane",
    rarity: "rare",
    type: "spell",
    onPlay: [
      {
        type: "secret",
      },
    ],
    secret: {
      when: "beforeHeroAttack",
      summon: "stone",
    },
  },
  {
    id: "battlecry",
    name: "战意沸腾",
    cost: 0,
    art: "banner",
    palette: "ember",
    rarity: "common",
    type: "spell",
    target: "friendlyMinion",
    onPlay: [
      {
        type: "buff",
        attack: 2,
        health: 0,
        to: "selected",
        duration: "turn",
      },
    ],
  },
  {
    id: "coin",
    name: "以太硬币",
    cost: 0,
    art: "orb",
    palette: "gold",
    rarity: "common",
    type: "spell",
    token: true,
    onPlay: [
      {
        type: "mana",
        amount: 1,
      },
    ],
  },
  {
    id: "pup",
    name: "幽灵狼",
    cost: 1,
    atk: 1,
    hp: 1,
    art: "wolf",
    palette: "void",
    rarity: "common",
    type: "minion",
    token: true,
  },
  {
    id: "spiritwolf",
    name: "灵狼",
    cost: 2,
    atk: 2,
    hp: 2,
    art: "wolf",
    palette: "nature",
    rarity: "common",
    type: "minion",
    tags: ["rush"],
    token: true,
  },
  {
    id: "skeleton",
    name: "骸骨",
    cost: 1,
    atk: 1,
    hp: 1,
    art: "reaper",
    palette: "steel",
    rarity: "common",
    type: "minion",
    token: true,
  },
  {
    id: "stone",
    name: "石卫",
    cost: 2,
    atk: 2,
    hp: 3,
    art: "golem",
    palette: "steel",
    rarity: "common",
    type: "minion",
    tags: ["taunt"],
    token: true,
  },
  {
    id: "sheep",
    name: "绵羊",
    cost: 1,
    atk: 1,
    hp: 1,
    art: "sheep",
    palette: "nature",
    rarity: "common",
    type: "minion",
    token: true,
  },
  {
    id: "recruit",
    name: "曙光新兵",
    cost: 1,
    atk: 1,
    hp: 1,
    art: "knight",
    palette: "gold",
    rarity: "common",
    type: "minion",
    token: true,
  },
  {
    id: "thorn",
    name: "荆棘树灵",
    cost: 1,
    atk: 1,
    hp: 2,
    art: "treant",
    palette: "nature",
    rarity: "common",
    type: "minion",
    tags: ["taunt"],
    token: true,
  },
];
if (typeof module !== "undefined") module.exports = EmberCardDefinitions;
