/* Authored cards. */
const EmberCardDefinitions = [
  {
    id: "spark",
    name: "引火学徒",
    cost: 1,
    atk: 1,
    hp: 3,
    art: "mage",
    palette: "ember",
    rarity: "common",
    type: "minion",
    onPlay: [
      {
        type: "damage",
        amount: 1,
        to: "enemyHero",
        spell: false,
      },
    ],
    class: "mage",
    triggers: [
      {
        event: "spellCast",
        effects: [
          {
            type: "buff",
            attack: 1,
            health: 0,
            to: "self",
            duration: "turn",
          },
        ],
        maxPerTurn: 3,
      },
    ],
  },
  {
    id: "squire",
    name: "晨曦侍从",
    cost: 1,
    atk: 1,
    hp: 2,
    art: "knight",
    palette: "gold",
    rarity: "common",
    type: "minion",
    tags: ["shield"],
    class: "paladin",
  },
  {
    id: "wolf",
    name: "月影幼狼",
    cost: 1,
    atk: 2,
    hp: 1,
    art: "wolf",
    palette: "ice",
    rarity: "common",
    type: "minion",
    onDeath: [
      {
        type: "summon",
        card: "pup",
        count: 1,
      },
    ],
    class: "ranger",
    tribe: "beast",
  },
  {
    id: "archer",
    name: "边境游侠",
    cost: 1,
    atk: 2,
    hp: 1,
    art: "archer",
    palette: "nature",
    rarity: "common",
    type: "minion",
    target: "enemyMinion",
    onPlay: [
      {
        type: "damage",
        amount: 1,
        to: "selected",
        spell: false,
      },
    ],
    class: "ranger",
  },
  {
    id: "guard",
    name: "铁誓卫士",
    cost: 2,
    atk: 2,
    hp: 3,
    art: "knight",
    palette: "steel",
    rarity: "common",
    type: "minion",
    tags: ["taunt"],
    class: "neutral",
  },
  {
    id: "oracle",
    name: "星界观测者",
    cost: 2,
    atk: 2,
    hp: 2,
    art: "mage",
    palette: "arcane",
    rarity: "rare",
    type: "minion",
    onPlay: [
      {
        type: "draw",
        count: 1,
      },
    ],
    class: "neutral",
  },
  {
    id: "wisp",
    name: "暮光精灵",
    cost: 2,
    atk: 3,
    hp: 2,
    art: "spirit",
    palette: "arcane",
    rarity: "rare",
    type: "minion",
    tags: ["spellpower"],
    class: "mage",
    triggers: [
      {
        event: "spellCast",
        effects: [
          {
            type: "damage",
            amount: 1,
            to: "enemyHero",
            spell: false,
          },
        ],
        maxPerTurn: 2,
      },
    ],
  },
  {
    id: "spider",
    name: "幽谷蛛后",
    cost: 2,
    atk: 1,
    hp: 3,
    art: "spider",
    palette: "nature",
    rarity: "rare",
    type: "minion",
    tags: ["poison"],
    class: "ranger",
    tribe: "beast",
  },
  {
    id: "sentinel",
    name: "烬翼斥候",
    cost: 2,
    atk: 2,
    hp: 3,
    art: "raven",
    palette: "ember",
    rarity: "common",
    type: "minion",
    tags: ["rush"],
    class: "neutral",
  },
  {
    id: "assassin",
    name: "夜幕刺客",
    cost: 3,
    atk: 4,
    hp: 2,
    art: "rogue",
    palette: "void",
    rarity: "rare",
    type: "minion",
    tags: ["stealth"],
    class: "ranger",
    triggers: [
      {
        event: "afterAttack",
        effects: [
          {
            type: "draw",
            count: 1,
          },
        ],
        maxPerTurn: 1,
      },
    ],
  },
  {
    id: "cleric",
    name: "曙光祭司",
    cost: 3,
    atk: 3,
    hp: 3,
    art: "mage",
    palette: "gold",
    rarity: "common",
    type: "minion",
    onPlay: [
      {
        type: "heal",
        amount: 4,
      },
    ],
    class: "neutral",
  },
  {
    id: "berserker",
    name: "赤岩狂战士",
    cost: 3,
    atk: 3,
    hp: 4,
    art: "knight",
    palette: "ember",
    rarity: "rare",
    type: "minion",
    tags: ["windfury"],
    class: "neutral",
  },
  {
    id: "golem",
    name: "符文石像",
    cost: 3,
    atk: 2,
    hp: 5,
    art: "golem",
    palette: "ice",
    rarity: "rare",
    type: "minion",
    tags: ["taunt"],
    onDeath: [
      {
        type: "armor",
        amount: 3,
      },
    ],
    class: "neutral",
  },
  {
    id: "leech",
    name: "血月行者",
    cost: 3,
    atk: 3,
    hp: 3,
    art: "rogue",
    palette: "blood",
    rarity: "rare",
    type: "minion",
    tags: ["lifesteal"],
    class: "ranger",
    tribe: "undead",
    triggers: [
      {
        event: "friendlyDeath",
        effects: [
          {
            type: "buff",
            attack: 1,
            health: 1,
            to: "self",
          },
        ],
        maxPerTurn: 2,
      },
    ],
  },
  {
    id: "treant",
    name: "古木守护者",
    cost: 4,
    atk: 3,
    hp: 6,
    art: "treant",
    palette: "nature",
    rarity: "common",
    type: "minion",
    tags: ["taunt"],
    class: "neutral",
  },
  {
    id: "phoenix",
    name: "不灭凤凰",
    cost: 4,
    atk: 4,
    hp: 3,
    art: "phoenix",
    palette: "ember",
    rarity: "epic",
    type: "minion",
    tags: ["reborn"],
    class: "mage",
  },
  {
    id: "rider",
    name: "霜牙狼骑",
    cost: 4,
    atk: 4,
    hp: 4,
    art: "wolf",
    palette: "ice",
    rarity: "rare",
    type: "minion",
    tags: ["rush"],
    class: "neutral",
    tribe: "beast",
  },
  {
    id: "necromancer",
    name: "亡者织梦师",
    cost: 4,
    atk: 3,
    hp: 4,
    art: "mage",
    palette: "void",
    rarity: "epic",
    type: "minion",
    onPlay: [
      {
        type: "summon",
        card: "skeleton",
        count: 2,
      },
    ],
    class: "ranger",
    tribe: "undead",
    triggers: [
      {
        event: "friendlyDeath",
        effects: [
          {
            type: "draw",
            count: 1,
          },
        ],
        maxPerTurn: 1,
      },
    ],
  },
  {
    id: "paladin",
    name: "圣光裁决者",
    cost: 5,
    atk: 4,
    hp: 5,
    art: "knight",
    palette: "gold",
    rarity: "epic",
    type: "minion",
    tags: ["taunt", "shield"],
    class: "paladin",
    triggers: [
      {
        event: "shieldLost",
        effects: [
          {
            type: "heal",
            amount: 2,
          },
        ],
        maxPerTurn: 2,
      },
    ],
  },
  {
    id: "titan",
    name: "玄铁泰坦",
    cost: 5,
    atk: 5,
    hp: 6,
    art: "golem",
    palette: "steel",
    rarity: "rare",
    type: "minion",
    onDeath: [
      {
        type: "summon",
        card: "stone",
        count: 1,
      },
    ],
    class: "neutral",
  },
  {
    id: "huntress",
    name: "荒野之矛",
    cost: 5,
    atk: 5,
    hp: 4,
    art: "archer",
    palette: "nature",
    rarity: "epic",
    type: "minion",
    tags: ["charge"],
    class: "ranger",
    tribe: "beast",
    triggers: [
      {
        event: "afterAttack",
        effects: [
          {
            type: "buff",
            attack: 1,
            health: 0,
            to: "friendlyBeasts",
            duration: "turn",
          },
        ],
        maxPerTurn: 1,
      },
    ],
  },
  {
    id: "dragon",
    name: "烬喉幼龙",
    cost: 6,
    atk: 6,
    hp: 6,
    art: "dragon",
    palette: "ember",
    rarity: "epic",
    type: "minion",
    onPlay: [
      {
        type: "damage",
        amount: 2,
        to: "enemyMinions",
        spell: false,
      },
    ],
    class: "neutral",
    tribe: "dragon",
  },
  {
    id: "reaper",
    name: "黯月收割者",
    cost: 6,
    atk: 5,
    hp: 5,
    art: "reaper",
    palette: "void",
    rarity: "epic",
    type: "minion",
    tags: ["lifesteal", "rush"],
    class: "ranger",
    tribe: "undead",
  },
  {
    id: "colossus",
    name: "远古山岳",
    cost: 7,
    atk: 7,
    hp: 9,
    art: "golem",
    palette: "nature",
    rarity: "epic",
    type: "minion",
    tags: ["taunt"],
    class: "neutral",
  },
  {
    id: "solaris",
    name: "逐日者·索拉",
    cost: 7,
    atk: 6,
    hp: 6,
    art: "knight",
    palette: "gold",
    rarity: "legendary",
    type: "minion",
    tags: ["shield"],
    onPlay: [
      {
        type: "buff",
        attack: 1,
        health: 1,
        to: "friendlyOthers",
      },
    ],
    class: "paladin",
    triggers: [
      {
        event: "turnEnd",
        effects: [
          {
            type: "grant",
            tag: "shield",
            to: "friendlyLowest",
          },
        ],
        maxPerTurn: 1,
      },
    ],
  },
  {
    id: "nyx",
    name: "星陨女王·妮克丝",
    cost: 8,
    atk: 6,
    hp: 8,
    art: "mage",
    palette: "arcane",
    rarity: "legendary",
    type: "minion",
    tags: ["spellpower"],
    onPlay: [
      {
        type: "draw",
        count: 2,
      },
    ],
    class: "mage",
    triggers: [
      {
        event: "spellCast",
        effects: [
          {
            type: "draw",
            count: 1,
          },
        ],
        maxPerTurn: 1,
      },
    ],
  },
  {
    id: "ashdragon",
    name: "终焰·阿什拉",
    cost: 9,
    atk: 8,
    hp: 8,
    art: "dragon",
    palette: "ember",
    rarity: "legendary",
    type: "minion",
    onPlay: [
      {
        type: "damage",
        amount: 3,
        to: "allOthers",
        spell: false,
      },
    ],
    class: "neutral",
    tribe: "dragon",
  },
  {
    id: "frostking",
    name: "白霜之王",
    cost: 8,
    atk: 7,
    hp: 8,
    art: "reaper",
    palette: "ice",
    rarity: "legendary",
    type: "minion",
    tags: ["taunt"],
    onPlay: [
      {
        type: "freeze",
        to: "enemyMinions",
      },
    ],
    class: "mage",
  },
  {
    id: "bolt",
    name: "星火箭",
    cost: 1,
    art: "bolt",
    palette: "ember",
    rarity: "common",
    type: "spell",
    target: "enemy",
    onPlay: [
      {
        type: "damage",
        amount: 2,
        to: "selected",
        spell: true,
      },
    ],
    class: "mage",
  },
  {
    id: "frostbolt",
    name: "寒霜之触",
    cost: 2,
    art: "crystal",
    palette: "ice",
    rarity: "rare",
    type: "spell",
    target: "enemy",
    onPlay: [
      {
        type: "damage",
        amount: 3,
        to: "selected",
        spell: true,
      },
      {
        type: "freeze",
        to: "selected",
      },
    ],
    class: "mage",
  },
  {
    id: "fireball",
    name: "陨火术",
    cost: 4,
    art: "meteor",
    palette: "ember",
    rarity: "rare",
    type: "spell",
    target: "enemy",
    onPlay: [
      {
        type: "damage",
        amount: 6,
        to: "selected",
        spell: true,
      },
    ],
    class: "mage",
  },
  {
    id: "nova",
    name: "冰封领域",
    cost: 3,
    art: "crystal",
    palette: "ice",
    rarity: "rare",
    type: "spell",
    onPlay: [
      {
        type: "freeze",
        to: "enemyMinions",
      },
      {
        type: "draw",
        count: 1,
      },
    ],
    class: "mage",
  },
  {
    id: "storm",
    name: "烈焰风暴",
    cost: 7,
    art: "meteor",
    palette: "ember",
    rarity: "epic",
    type: "spell",
    onPlay: [
      {
        type: "damage",
        amount: 4,
        to: "enemyMinions",
        spell: true,
      },
    ],
    class: "mage",
  },
  {
    id: "wisdom",
    name: "星界密卷",
    cost: 3,
    art: "book",
    palette: "arcane",
    rarity: "common",
    type: "spell",
    onPlay: [
      {
        type: "draw",
        count: 2,
      },
    ],
    class: "mage",
  },
  {
    id: "blessing",
    name: "黎明祝福",
    cost: 2,
    art: "sigil",
    palette: "gold",
    rarity: "common",
    type: "spell",
    target: "friendlyMinion",
    onPlay: [
      {
        type: "buff",
        attack: 2,
        health: 2,
        to: "selected",
      },
    ],
    class: "paladin",
  },
  {
    id: "renew",
    name: "生命之泉",
    cost: 2,
    art: "potion",
    palette: "nature",
    rarity: "common",
    type: "spell",
    onPlay: [
      {
        type: "heal",
        amount: 6,
      },
      {
        type: "draw",
        count: 1,
      },
    ],
    class: "paladin",
  },
  {
    id: "execute",
    name: "暗影湮灭",
    cost: 5,
    art: "reaper",
    palette: "void",
    rarity: "epic",
    type: "spell",
    target: "enemyMinion",
    onPlay: [
      {
        type: "destroy",
        to: "selected",
      },
    ],
    class: "ranger",
  },
  {
    id: "silence",
    name: "遗忘咒印",
    cost: 1,
    art: "sigil",
    palette: "void",
    rarity: "rare",
    type: "spell",
    target: "minion",
    onPlay: [
      {
        type: "silence",
        to: "selected",
      },
    ],
    class: "neutral",
  },
  {
    id: "rally",
    name: "王者号令",
    cost: 4,
    art: "banner",
    palette: "gold",
    rarity: "epic",
    type: "spell",
    onPlay: [
      {
        type: "buff",
        attack: 2,
        health: 2,
        to: "friendlyMinions",
      },
    ],
    class: "paladin",
  },
  {
    id: "wolves",
    name: "群狼呼唤",
    cost: 3,
    art: "wolf",
    palette: "nature",
    rarity: "rare",
    type: "spell",
    onPlay: [
      {
        type: "summon",
        card: "spiritwolf",
        count: 2,
        requireSpace: true,
      },
    ],
    class: "ranger",
  },
  {
    id: "shield",
    name: "圣光庇佑",
    cost: 1,
    art: "sigil",
    palette: "gold",
    rarity: "common",
    type: "spell",
    target: "friendlyMinion",
    onPlay: [
      {
        type: "grant",
        tag: "shield",
        to: "selected",
      },
    ],
    class: "paladin",
  },
  {
    id: "lifedrain",
    name: "灵魂虹吸",
    cost: 3,
    art: "orb",
    palette: "blood",
    rarity: "rare",
    type: "spell",
    target: "enemy",
    onPlay: [
      {
        type: "damage",
        amount: 3,
        to: "selected",
        spell: true,
      },
      {
        type: "heal",
        amount: 3,
      },
    ],
    class: "ranger",
  },
  {
    id: "dagger",
    name: "银月双刃",
    cost: 2,
    atk: 2,
    hp: 2,
    art: "sword",
    palette: "steel",
    rarity: "rare",
    type: "weapon",
    class: "ranger",
  },
  {
    id: "sunblade",
    name: "日耀圣剑",
    cost: 4,
    atk: 4,
    hp: 2,
    art: "sword",
    palette: "gold",
    rarity: "epic",
    type: "weapon",
    tags: ["lifesteal"],
    class: "paladin",
  },
  {
    id: "polymorph",
    name: "迷途化形",
    cost: 4,
    art: "sheep",
    palette: "arcane",
    rarity: "rare",
    type: "spell",
    target: "enemyMinion",
    onPlay: [
      {
        type: "transform",
        card: "sheep",
        to: "selected",
      },
    ],
    class: "mage",
  },
  {
    id: "discovery",
    name: "虚空洞见",
    cost: 2,
    art: "orb",
    palette: "arcane",
    rarity: "epic",
    type: "spell",
    onPlay: [
      {
        type: "discover",
        count: 3,
        cardType: "spell",
      },
    ],
    class: "mage",
  },
  {
    id: "ambush",
    name: "镜像伏击",
    cost: 2,
    art: "mirror",
    palette: "arcane",
    rarity: "rare",
    type: "spell",
    onPlay: [
      {
        type: "secret",
      },
    ],
    secret: {
      when: "beforeHeroAttack",
      summon: "stone",
    },
    class: "mage",
  },
  {
    id: "battlecry",
    name: "战意沸腾",
    cost: 0,
    art: "banner",
    palette: "ember",
    rarity: "common",
    type: "spell",
    target: "friendlyMinion",
    onPlay: [
      {
        type: "buff",
        attack: 2,
        health: 0,
        to: "selected",
        duration: "turn",
      },
    ],
    class: "ranger",
  },
  {
    id: "coin",
    name: "以太硬币",
    cost: 0,
    art: "orb",
    palette: "gold",
    rarity: "common",
    type: "spell",
    token: true,
    onPlay: [
      {
        type: "mana",
        amount: 1,
      },
    ],
    class: "neutral",
  },
  {
    id: "pup",
    name: "幽灵狼",
    cost: 1,
    atk: 1,
    hp: 1,
    art: "wolf",
    palette: "void",
    rarity: "common",
    type: "minion",
    token: true,
    class: "neutral",
    tribe: "beast",
  },
  {
    id: "spiritwolf",
    name: "灵狼",
    cost: 2,
    atk: 2,
    hp: 2,
    art: "wolf",
    palette: "nature",
    rarity: "common",
    type: "minion",
    tags: ["rush"],
    token: true,
    class: "neutral",
    tribe: "beast",
  },
  {
    id: "skeleton",
    name: "骸骨",
    cost: 1,
    atk: 1,
    hp: 1,
    art: "reaper",
    palette: "steel",
    rarity: "common",
    type: "minion",
    token: true,
    class: "neutral",
    tribe: "undead",
  },
  {
    id: "stone",
    name: "石卫",
    cost: 2,
    atk: 2,
    hp: 3,
    art: "golem",
    palette: "steel",
    rarity: "common",
    type: "minion",
    tags: ["taunt"],
    token: true,
    class: "neutral",
  },
  {
    id: "sheep",
    name: "绵羊",
    cost: 1,
    atk: 1,
    hp: 1,
    art: "sheep",
    palette: "nature",
    rarity: "common",
    type: "minion",
    token: true,
    class: "neutral",
  },
  {
    id: "recruit",
    name: "曙光新兵",
    cost: 1,
    atk: 1,
    hp: 1,
    art: "knight",
    palette: "gold",
    rarity: "common",
    type: "minion",
    token: true,
    class: "neutral",
  },
  {
    id: "thorn",
    name: "荆棘树灵",
    cost: 1,
    atk: 1,
    hp: 2,
    art: "treant",
    palette: "nature",
    rarity: "common",
    type: "minion",
    tags: ["taunt"],
    token: true,
    class: "neutral",
  },
  {
    id: "counterspell",
    name: "破法之镜",
    cost: 3,
    class: "mage",
    palette: "arcane",
    type: "spell",
    rarity: "rare",
    art: "sigil",
    set: "tavern_oaths",
    onPlay: [
      {
        type: "secret",
      },
    ],
    secret: {
      when: "beforeSpell",
      counter: true,
    },
  },
  {
    id: "icebarrier",
    name: "霜晶壁垒",
    cost: 2,
    class: "mage",
    palette: "ice",
    type: "spell",
    rarity: "rare",
    art: "sigil",
    set: "tavern_oaths",
    onPlay: [
      {
        type: "secret",
      },
    ],
    secret: {
      when: "beforeHeroAttack",
      armor: 8,
    },
  },
  {
    id: "muster",
    name: "黎明集结",
    cost: 3,
    class: "paladin",
    palette: "gold",
    type: "spell",
    rarity: "rare",
    art: "sigil",
    set: "tavern_oaths",
    onPlay: [
      {
        type: "summon",
        card: "recruit",
        count: 3,
        requireSpace: true,
      },
    ],
  },
  {
    id: "absolution",
    name: "誓约祷言",
    cost: 3,
    class: "paladin",
    palette: "gold",
    type: "spell",
    rarity: "rare",
    art: "sigil",
    set: "tavern_oaths",
    onPlay: [
      {
        type: "draw",
        count: 2,
      },
      {
        type: "grant",
        tag: "shield",
        to: "friendlyLowest",
      },
    ],
  },
  {
    id: "tracking",
    name: "月径追踪",
    cost: 2,
    class: "ranger",
    palette: "nature",
    type: "spell",
    rarity: "rare",
    art: "sigil",
    set: "tavern_oaths",
    onPlay: [
      {
        type: "drawFiltered",
        count: 2,
        cardType: "minion",
        tribe: "beast",
      },
    ],
  },
  {
    id: "sabotage",
    name: "断刃伏击",
    cost: 2,
    class: "ranger",
    palette: "steel",
    type: "spell",
    rarity: "rare",
    art: "sigil",
    set: "tavern_oaths",
    onPlay: [
      {
        type: "destroyWeapon",
      },
      {
        type: "draw",
        count: 1,
      },
    ],
  },
  {
    id: "soulguide",
    name: "渡魂引路人",
    cost: 3,
    atk: 3,
    hp: 4,
    type: "minion",
    class: "ranger",
    art: "spirit",
    palette: "void",
    rarity: "rare",
    set: "moon_covenant",
    onDeath: [
      {
        type: "draw",
        count: 1,
      },
    ],
  },
  {
    id: "moonfox",
    name: "银灯灵狐",
    cost: 1,
    atk: 1,
    hp: 2,
    type: "minion",
    class: "ranger",
    art: "spirit",
    palette: "void",
    rarity: "rare",
    set: "moon_covenant",
    tribe: "beast",
    onDeath: [
      {
        type: "heal",
        amount: 2,
      },
    ],
  },
  {
    id: "duskstag",
    name: "暮角契鹿",
    cost: 3,
    atk: 3,
    hp: 4,
    type: "minion",
    class: "ranger",
    art: "spirit",
    palette: "void",
    rarity: "rare",
    set: "moon_covenant",
    tribe: "beast",
    onDeath: [
      {
        type: "armor",
        amount: 2,
      },
    ],
  },
  {
    id: "graveoffering",
    name: "归月献仪",
    cost: 2,
    type: "spell",
    class: "ranger",
    art: "sigil",
    palette: "void",
    rarity: "rare",
    set: "moon_covenant",
    onPlay: [
      {
        type: "sacrifice",
        to: "selected",
      },
      {
        type: "draw",
        count: 2,
      },
    ],
    target: "friendlyMinion",
  },
  {
    id: "mooncall",
    name: "月径结伴",
    cost: 3,
    type: "spell",
    class: "ranger",
    art: "sigil",
    palette: "void",
    rarity: "rare",
    set: "moon_covenant",
    onPlay: [
      {
        type: "summon",
        card: "moonfox",
        count: 1,
      },
      {
        type: "summon",
        card: "wolf",
        count: 1,
      },
    ],
  },
  {
    id: "soultether",
    name: "系魂银线",
    cost: 2,
    type: "spell",
    class: "ranger",
    art: "sigil",
    palette: "void",
    rarity: "rare",
    set: "moon_covenant",
    onPlay: [
      {
        type: "grant",
        tag: "reborn",
        to: "selected",
      },
    ],
    target: "friendlyMinion",
  },
  {
    id: "moonlance",
    name: "碎月长矛",
    cost: 3,
    type: "spell",
    class: "ranger",
    art: "sigil",
    palette: "void",
    rarity: "rare",
    set: "moon_covenant",
    onPlay: [
      {
        type: "damage",
        amount: 4,
        to: "selected",
        spell: true,
      },
    ],
    target: "enemyMinion",
  },
  {
    id: "stillness",
    name: "寂静封印",
    cost: 3,
    type: "spell",
    class: "neutral",
    art: "sigil",
    palette: "void",
    rarity: "rare",
    set: "moon_covenant",
    onPlay: [
      {
        type: "silence",
        to: "selected",
      },
      {
        type: "damage",
        amount: 2,
        to: "selected",
        spell: false,
      },
    ],
    target: "enemyMinion",
  },
  {
    id: "eclipsewolf",
    name: "蚀月狼王",
    cost: 7,
    atk: 5,
    hp: 5,
    type: "minion",
    class: "ranger",
    art: "spirit",
    palette: "void",
    rarity: "legendary",
    set: "moon_covenant",
    token: true,
    tribe: "beast",
    tags: ["rush"],
    contract: {
      souls: 2,
      deaths: 3,
      divine: false,
    },
    onPlay: [
      {
        type: "damage",
        amount: 2,
        to: "enemyMinions",
        spell: false,
      },
    ],
  },
  {
    id: "moonguard",
    name: "守灯巨兽",
    cost: 5,
    atk: 3,
    hp: 7,
    type: "minion",
    class: "ranger",
    art: "spirit",
    palette: "void",
    rarity: "legendary",
    set: "moon_covenant",
    token: true,
    tribe: "beast",
    tags: ["taunt"],
    contract: {
      souls: 2,
      deaths: 3,
      divine: false,
    },
    onPlay: [
      {
        type: "heal",
        amount: 4,
      },
    ],
  },
  {
    id: "selmyra",
    name: "冥月神·瑟弥拉",
    cost: 9,
    atk: 7,
    hp: 9,
    type: "minion",
    class: "ranger",
    art: "spirit",
    palette: "void",
    rarity: "legendary",
    set: "moon_covenant",
    token: true,
    tribe: "undead",
    contract: {
      souls: 4,
      deaths: 8,
      divine: true,
    },
    onPlay: [
      {
        type: "summon",
        card: "spiritwolf",
        count: 2,
      },
    ],
    triggers: [
      {
        event: "friendlyDeath",
        maxPerTurn: 2,
        effects: [
          {
            type: "buff",
            attack: 1,
            health: 0,
            to: "self",
          },
        ],
      },
    ],
  },
];
if (typeof module !== "undefined") module.exports = EmberCardDefinitions;
