/* Theme data only: semantic artwork, lighting and composition. No game state. */
const EmberThemeDefinition = Object.freeze({
  id: "silverblue",
  name: "星海银蓝",
  title: "烬域 · 风起之境",
  copy: Object.freeze({
    eyebrow: "旅人的星海序章",
    subtitle: "灰烬酒馆",
    tagline: "每一手，都是新的故事。",
    footer: "EMBERFALL / A JOURNEY AMONG STARS",
  }),
  art: Object.freeze({
    home: "asset:themes/silverblue/home.webp",
    homeLogo: "asset:ui/home-reference-v1/final/logo.webp",
    homePrimary: "asset:ui/home-reference-v1/final/button-primary.webp",
    homeSecondary: "asset:ui/home-reference-v1/final/button-secondary.webp",
    homePortal: "asset:ui/home-reference-v1/final/card-portal.webp",
    homeTree: "asset:ui/home-reference-v1/final/card-tree.webp",
    homeDragon: "asset:ui/home-reference-v1/final/card-dragon.webp",

    polishCardFrame: "asset:ui/detail-polish-v1/card-silver.webp",
    polishButtonCapsule: "asset:ui/detail-polish-v1/button-capsule.webp",
    polishButtonNight: "asset:ui/detail-polish-v1/button-night.webp",
    polishSelectionPanel: "asset:ui/detail-polish-v1/selection-panel.webp",
    referenceMulligan: "asset:ui/page-reference-v1/07-mulligan.webp",
    referenceRewards: "asset:ui/page-reference-v1/08-rewards.webp",
    referenceResult: "asset:ui/page-reference-v1/09-result.webp",
    referenceSettings: "asset:ui/page-reference-v1/10-settings.webp",
    referenceDetail: "asset:ui/page-reference-v1/14-detail.webp",
    referenceDiscover: "asset:ui/page-reference-v1/14-discover.webp",
    referenceConfirm: "asset:ui/page-reference-v1/14-confirm.webp",
    referenceGuide: "asset:ui/page-reference-v1/11-guide.webp",
    relicHeart: "asset:ui/page-reference-v1/relic-heart.webp",
    relicLens: "asset:ui/page-reference-v1/relic-lens.webp",
    relicCrown: "asset:ui/page-reference-v1/relic-crown.webp",
    victorySigil: "asset:ui/page-reference-v1/victory-sigil.webp",
    defeatBackground: "asset:ui/page-reference-v1/defeat-background.webp",
    battle_warden: "asset:scenes/boss-topdown-v1/warden.webp",
    battle_queen: "asset:scenes/boss-topdown-v1/queen.webp",
    battle_oracle: "asset:scenes/boss-topdown-v1/oracle.webp",
    battle_frost: "asset:scenes/boss-topdown-v1/frost.webp",
    battle_dragon: "asset:scenes/boss-topdown-v1/dragon.webp",
    battle_moonkeeper: "asset:scenes/boss-topdown-v1/moonkeeper.webp",
    map: "asset:themes/silverblue/map.webp",
    backdrop: "asset:themes/silverblue/backdrop.webp",
    mage: "asset:themes/silverblue/mage.webp",
    paladin: "asset:themes/silverblue/paladin.webp",
    ranger: "asset:themes/silverblue/ranger.webp",
    morla: "asset:themes/silverblue/morla.webp",
    goddess: "asset:themes/silverblue/goddess.webp",
  }),
  scenes: Object.freeze({
    home: Object.freeze({
      art: "home",
      focus: [0.52, 0.5],
      portraitFocus: [0.54, 0.5],
      shade: 0.04,
    }),
    battle: Object.freeze({
      art: "battle_warden",
      focus: [0.5, 0.5],
      portraitFocus: [0.5, 0.48],
      shade: 0.1,
    }),
    backdrop: Object.freeze({
      art: "backdrop",
      focus: [0.5, 0.5],
      portraitFocus: [0.5, 0.5],
      shade: 0.15,
    }),
  }),
  encounters: Object.freeze({
    warden: "battle_warden",
    queen: "battle_queen",
    oracle: "battle_oracle",
    frost: "battle_frost",
    dragon: "battle_dragon",
    moonkeeper: "battle_moonkeeper",
    practice: "home",
  }),
  scenery: Object.freeze([
    {
      id: "chimney",
      name: "观星长廊",
      hint: "轻触铜灯，点亮桌边的暖光",
      focus: [145, 160],
      warm: true,
      box: { left: "12px", top: "58px", width: "240px", height: "217px" },
    },
    {
      id: "crystals",
      name: "星辉观测台",
      hint: "轻拨星环，让星光落在掌心",
      focus: [1430, 160],
      box: { left: "1390px", top: "63px", width: "180px", height: "211px" },
    },
    {
      id: "tree",
      name: "流云星石",
      hint: "轻触星石，听见清澈的回声",
      focus: [125, 690],
      box: { left: "18px", top: "510px", width: "175px", height: "232px" },
    },
    {
      id: "forge",
      name: "旅人铜灯",
      hint: "轻触铜灯，唤起温暖的光",
      focus: [1460, 700],
      warm: true,
      box: { left: "1475px", top: "710px", width: "110px", height: "120px" },
    },
  ]),
  light: Object.freeze({
    ambient: "#101a30",
    glow: "#b6ddff",
    warm: "#f1c891",
    line: "#beddf3",
  }),
});
