"""Pack verified local Foley for both embedded and content-addressed builds."""
from pathlib import Path
import base64
import hashlib
import json

ROOT = Path(__file__).resolve().parents[1]


def generate():
    folder = ROOT / 'assets/audio'
    manifest = json.loads((folder / 'manifest.json').read_text())
    bank = {}
    for asset in manifest['assets']:
        data = (folder / asset['path']).read_bytes()
        if hashlib.sha256(data).hexdigest() != asset['sha256']:
            raise ValueError(f"Audio hash mismatch: {asset['id']}")
        if asset['id'] in bank:
            raise ValueError(f"Duplicate audio ID: {asset['id']}")
        bank[asset['id']] = {'src': 'data:audio/mpeg;base64,' + base64.b64encode(data).decode(),
                             'duration': asset['metrics']['decodedDurationSeconds']}
    (ROOT / 'src/audio-assets.js').write_text(
        '/* Generated by tools/audio_assets.py. Kenney CC0: assets/audio/CREDITS.md. */\n'
        'const EmberSoundBank = Object.freeze(' + json.dumps(bank, separators=(',', ':')) + ');\n')


if __name__ == '__main__':
    generate()
