"""Collect the layers the amber card renderer (src/presentation/amber-volume.js) seals inside the resin.

    uv run --python 3.12 --no-project --with pillow --with numpy python tools/bake_amber_layers.py

Each card has a scene (bg), a figure with alpha (body), an optional held prop (front) and a depth map
(R scene, G figure, B prop). Two sources, the better one wins per card:
  * tools/amber_relayer/work/<id>/out/  re-layered by tools/amber_relayer (a real matte, a painted plate behind
    the figure, so a turn shows the whole face);
  * art/amber/<id>-*.webp               what is already there (the automatic depth-threshold split these cards started with),
    kept until a card has been re-layered. A card with neither seals its flat illustration at runtime.
Writes art/amber/<id>-{bg,body,front,depth}.webp and the registry src/amber-layers.js (follow: how far the scene
follows the figure; the automatic split needs it, a re-layered card does not).
"""
import json
import shutil
from pathlib import Path

import numpy as np
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
WORK = ROOT / "tools/amber_relayer/work"
OUT = ROOT / "art/amber"
REGISTRY = ROOT / "src/amber-layers.js"
IDS = sorted(p.stem for p in (ROOT / "assets/anime/overrides").glob("*.png"))


def save(img, path, **kw):
    img.save(path, "WEBP", method=6, **kw)


def nonempty(img):
    return bool((np.asarray(img.convert("RGBA").resize((64, 80)))[..., 3] > 3).any())


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    registry = {}
    for cid in IDS:
        out = WORK / cid / "out"
        entry = {}
        if (out / "body.png").is_file():
            save(Image.open(out / "bg.png").convert("RGB"), OUT / f"{cid}-bg.webp", quality=80)
            save(Image.open(out / "body.png").convert("RGBA"), OUT / f"{cid}-body.webp", quality=82, alpha_quality=85)
            save(Image.open(out / "depth.png").convert("RGB"), OUT / f"{cid}-depth.webp", quality=88)
            front = Image.open(out / "front.png").convert("RGBA")
            if nonempty(front):
                save(front, OUT / f"{cid}-front.webp", quality=82, alpha_quality=85)
                entry["front"] = True
            entry["follow"] = 0
        elif (OUT / f"{cid}-body.webp").is_file():
            entry["follow"] = 0.85
            if (OUT / f"{cid}-front.webp").is_file():
                entry["front"] = True
        else:
            continue
        registry[cid] = entry
    lines = ["/* Generated by tools/bake_amber_layers.py. The layers of every card's sealed scene (art/amber/<id>-{bg,body,front,depth}.webp).",
             " * follow: how far the scene behind the figure follows it; front: the card has a held prop layer. The single-file build",
             " * leaves this registry empty (about 20 MB of layers); its cards then seal their flat illustration instead. */",
             "const EmberAmberLayers = Object.freeze({"]
    for cid, e in registry.items():
        kinds = ["bg", "body"] + (["front"] if e.get("front") else []) + ["depth"]
        files = ", ".join(f'{k}: "asset:amber/{cid}-{k}.webp"' for k in kinds)
        lines.append(f'  {cid}: {{ follow: {e["follow"]}, {files} }},')
    lines += ["});", "if (typeof module !== \"undefined\") module.exports = EmberAmberLayers;", ""]
    REGISTRY.write_text("\n".join(lines))
    size = sum(p.stat().st_size for p in OUT.glob("*.webp"))
    print(f"{len(registry)} cards, {len(list(OUT.glob('*.webp')))} files, {size/1e6:.1f} MB; re-layered: {sum(1 for c in registry if registry[c]['follow'] == 0)}")


if __name__ == "__main__":
    main()
