#!/usr/bin/env python3
"""Slice the eight user-approved atlases, omit captions, embed all 56 images.
This is deterministic image processing, NOT generation or super-resolution.
Rebuild from assets/anime/sources/*.png. Runtime never needs the source sheets.
"""
from pathlib import Path
from PIL import Image, ImageOps
import json, base64, hashlib, subprocess

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'assets'/'anime'; SRC=OUT/'sources'
SHEETS=[
 ('01-apprentices.png',['spark','squire','wolf','archer','guard','oracle','wisp']),
 ('02-vanguards.png',['spider','sentinel','assassin','cleric','berserker','golem','leech']),
 ('03-guardians.png',['treant','phoenix','rider','necromancer','paladin','titan','huntress']),
 ('04-legends.png',['dragon','reaper','colossus','solaris','nyx','ashdragon','frostking']),
 ('05-elements.png',['bolt','frostbolt','fireball','nova','storm','wisdom','blessing']),
 ('06-rituals.png',['renew','execute','silence','rally','wolves','shield','lifedrain']),
 ('07-relics.png',['dagger','sunblade','polymorph','discovery','ambush','battlecry','coin']),
 ('08-companions.png',['pup','spiritwolf','skeleton','stone','sheep','recruit','thorn']),
]
# Same layout in all approved sheets. Conservative interior windows; captions
# and ivory gutters are outside the crop. Fractions are resolution-independent.
XS=[(.012,.2465),(.26,.4925),(.5075,.741),(.7545,.9875)]
YS=[(.012,.432),(.504,.925)]
SIZE=(336,448) # 3:4, at or below native panel resolution. No synthetic enlargement.

def sha(data):return hashlib.sha256(data).hexdigest()

def build():
 OUT.mkdir(parents=True,exist_ok=True)
 data=json.loads(subprocess.check_output(['node','-e',"console.log(JSON.stringify(require('./src/data.js')))"],cwd=ROOT))
 cards={c['id']:c for c in data['cards']}
 cache={}; items={}
 for fn,ids in SHEETS:
  path=SRC/fn
  im=Image.open(path).convert('RGB');w,h=im.size
  for i,cid in enumerate(ids):
   x0,x1=XS[i%4];y0,y1=YS[i//4]
   box=(round(w*x0),round(h*y0),round(w*x1),round(h*y1))
   crop=im.crop(box)
   assert crop.width>=SIZE[0] and crop.height>=SIZE[1],(fn,cid,box)
   crop=ImageOps.fit(crop,SIZE,method=Image.Resampling.LANCZOS,centering=(.5,.5))
   dest=OUT/f'{cid}.webp';crop.save(dest,'WEBP',quality=91,method=6)
   blob=dest.read_bytes()
   cache[cid]='data:image/webp;base64,'+base64.b64encode(blob).decode()
   items[cid]={'name':cards[cid]['name'],'type':cards[cid]['type'],'token':bool(cards[cid].get('token')),
    'source':f'sources/{fn}','sourceSHA256':sha(path.read_bytes()),'cropBox':box,
    'cropNativeSize':[box[2]-box[0],box[3]-box[1]],'outputSize':SIZE,
    'file':dest.name,'bytes':len(blob),'sha256':sha(blob),'method':'interior crop, caption removal, proportional downsampling, WebP; no upscaling'}
 assert set(cache)==set(cards),{'missing':list(set(cards)-set(cache)),'extra':list(set(cache)-set(cards))}
 assert len({v['sha256'] for v in items.values()})==56,'Duplicate art assets'
 manifest={'version':'0.6.0','cards':56,'collectible':48,'tokens':8,'sourceAtlases':8,
  'description':'Every card has a separate panel from the user-approved anime atlas set. Hero/Boss portraits deliberately reuse matching panels, listed separately in runtime routing. Frames and scenery are retained from v0.5.',
  'items':items}
 (OUT/'manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
 (ROOT/'src'/'anime-assets.js').write_text('/* All 56 approved anime card panels, caption-free. Generated by tools/build_anime_assets.py. */\nconst AnimeAssets=Object.freeze('+json.dumps(cache,separators=(',',':'))+');\n',encoding='utf-8')
 print(f'Built {len(cache)} unique card images, {sum(v["bytes"] for v in items.values()):,} WebP bytes')

if __name__=='__main__':build()
