#!/usr/bin/env python3
"""Embed only the current textures and the four gallery illustrations."""
from pathlib import Path
import base64
import json
ROOT = Path(__file__).resolve().parents[1]
KEYS = ['building-brewery', 'building-observatory', 'building-mine', 'building-forge', 'paper', 'wood', 'leaf-seal']
def pack():
    cache = {}
    for key in KEYS:
        suffix = 'svg' if key == 'leaf-seal' else 'webp'
        mime = 'svg+xml' if suffix == 'svg' else suffix
        blob = (ROOT / 'assets/windborne' / f'{key}.{suffix}').read_bytes()
        cache[key] = f'data:image/{mime};base64,' + base64.b64encode(blob).decode()
    (ROOT / 'src/world-assets.js').write_text('/* Generated by tools/pack_world_assets.py. */\nconst WindborneAssets=Object.freeze(' + json.dumps(cache, separators=(',', ':')) + ');\n')
    print(f'Packed {len(cache)} current world/gallery assets')
if __name__ == '__main__':
    pack()
