#!/usr/bin/env python3
"""Pack current card WebPs; optionally replace ONE illustration with provenance.

python3 tools/pack_card_assets.py
python3 tools/pack_card_assets.py --card cleric --image /path/art.png --source-note 'Approved replacement'

Packing uses stdlib + Node. Replacement additionally uses declared Pillow.
The eight-sheet crop command calls this same packer; persistent overrides win.
"""
from pathlib import Path
import argparse
import base64
import hashlib
import json
import shutil
import subprocess

ROOT = Path(__file__).resolve().parents[1]
ART = ROOT / 'assets/anime'
OVERRIDES = ART / 'overrides.json'

def sha(blob):
    return hashlib.sha256(blob).hexdigest()

def pack():
    data = json.loads(subprocess.check_output(['node', '-e', 'console.log(JSON.stringify(require("./src/data.js")))'], cwd=ROOT))
    cards = {c['id']: c for c in data['cards']}
    manifest = json.loads((ART / 'manifest.json').read_text())
    overrides = json.loads(OVERRIDES.read_text()) if OVERRIDES.exists() else {}
    if set(manifest['items']) != set(cards):
        raise ValueError('Manifest IDs must exactly match card definitions')
    cache = {}
    for cid, c in cards.items():
        m = manifest['items'][cid]
        if cid in overrides:
            from PIL import Image, ImageOps
            entry = overrides[cid]
            source = ART / entry['source']
            with Image.open(source) as image:
                native = list(image.size)
                if min(native) < 336:
                    raise ValueError(f'{cid}: source too small')
                output = ImageOps.fit(image.convert('RGB'), (336, 448), method=Image.Resampling.LANCZOS)
                output.save(ART / m['file'], 'WEBP', quality=91, method=6)
            m.update(source=entry['source'], sourceSHA256=sha(source.read_bytes()),
                     sourceNote=entry['note'], cropNativeSize=native,
                     cropBox=None, method='Approved individual source; proportional crop and WebP')
        blob = (ART / m['file']).read_bytes()
        if cid not in overrides and sha(blob) != m['sha256']:
            raise ValueError(f'{cid}: unrecorded image edit; use --card/--image/--source-note')
        m.update(name=c['name'], type=c['type'], token=bool(c.get('token')),
                 bytes=len(blob), sha256=sha(blob), outputSize=[336, 448])
        cache[cid] = 'data:image/webp;base64,' + base64.b64encode(blob).decode()
    if len({m['sha256'] for m in manifest['items'].values()}) != len(cards):
        raise ValueError('Every card requires distinct artwork')
    manifest.update(cards=len(cards), collectible=sum(not c.get('token') for c in cards.values()),
                    tokens=sum(bool(c.get('token')) for c in cards.values()),
                    sourceAtlases=len({m['source'] for m in manifest['items'].values() if m['source'].startswith('sources/')}))
    (ART / 'manifest.json').write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + '\n')
    (ROOT / 'src/anime-assets.js').write_text('/* Generated by tools/pack_card_assets.py; do not edit. */\nconst AnimeAssets=Object.freeze(' + json.dumps(cache, separators=(',', ':')) + ');\n')
    relics = json.loads((ART / 'non-card-relics.json').read_text())
    relics = {key.split('|')[-1]: image for key, image in relics.items()}
    if set(relics) != {r['id'] for r in data['relics']}:
        raise ValueError('Relic images must match campaign relic IDs')
    (ROOT / 'src/relic-assets.js').write_text('/* Generated from assets/anime/non-card-relics.json. */\nconst EmberRelicAssets=Object.freeze(' + json.dumps(relics, separators=(',', ':')) + ');\n')
    print(f'Packed {len(cards)} unique card images; {len(overrides)} individual overrides')

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--card')
    parser.add_argument('--image', type=Path)
    parser.add_argument('--source-note')
    args = parser.parse_args()
    if any([args.card, args.image, args.source_note]):
        if not all([args.card, args.image, args.source_note]):
            parser.error('--card, --image and --source-note must be supplied together')
        manifest = json.loads((ART / 'manifest.json').read_text())
        if args.card not in manifest['items']:
            parser.error('Unknown card ID')
        from PIL import Image
        with Image.open(args.image) as image:
            if image.width < 336 or image.height < 448:
                parser.error('Source must be at least 336 by 448 pixels')
        target = ART / 'overrides' / (args.card + args.image.suffix.lower())
        target.parent.mkdir(exist_ok=True)
        if target.resolve() != args.image.resolve():
            shutil.copyfile(args.image, target)
        entries = json.loads(OVERRIDES.read_text()) if OVERRIDES.exists() else {}
        entries[args.card] = {'source': str(target.relative_to(ART)), 'note': args.source_note}
        OVERRIDES.write_text(json.dumps(entries, ensure_ascii=False, indent=2) + '\n')
    pack()

if __name__ == '__main__':
    main()
