"""Embed the battlefield's painted pixel sprites (assets/sprites/<figure id>.png, true pixel size, transparent
background) into src/presentation/voxel/sprite-art.js as data URLs for EmberSpriteFigures. Standard library only.

    python3 tools/sprite_art.py
"""
import base64, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC, OUT = ROOT / "assets" / "sprites", ROOT / "src" / "presentation" / "voxel" / "sprite-art.js"

lines = ["/* Generated by tools/sprite_art.py from assets/sprites/*.png — do not edit. */", "const EmberSpriteArt = Object.freeze({"]
for png in sorted(SRC.glob("*.png")):
    lines.append(f'  {png.stem}: "data:image/png;base64,{base64.b64encode(png.read_bytes()).decode()}",')
lines.append("});")
OUT.write_text("\n".join(lines) + "\n")
print(f"{OUT.relative_to(ROOT)}: {len(lines) - 3} sprites, {OUT.stat().st_size // 1024} KB")
